package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the AD_REPORT table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="AD_REPORT"
 */
public abstract class BaseAdReport  implements Serializable {

	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_REPORT_TYPE = "ReportType";
	public static String PROP_AUTO_UPDATE = "AutoUpdate";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_FILE_URL = "FileUrl";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_PREVIEW_URL = "PreviewUrl";
	public static String PROP_MASTER_TEMPLATE_ID = "MasterTemplateId";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_MODIFIERID = "Modifierid";
	public static String PROP_ALLOW_FG = "AllowFg";
	public static String PROP_AD_TABLE_ID = "AdTableId";
	public static String PROP_IS_MASTER = "IsMaster";
	public static String PROP_NAME = "Name";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adTableId;
	private java.lang.Integer _adClientId;
	private java.lang.Integer _modifierid;
	private java.lang.String _autoUpdate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isMaster;
	private java.lang.String _reportType;
	private java.lang.String _allowFg;
	private java.lang.Integer _masterTemplateId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _isActive;
	private java.lang.String _fileUrl;
	private java.util.Date _creationDate;
	private java.lang.Integer _ownerId;
	private java.lang.String _name;
	private java.lang.String _description;
	private java.lang.String _previewUrl;


	// constructors
	public BaseAdReport () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAdReport (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAdReport (
		java.lang.Integer _id,
		java.lang.String _isMaster,
		java.lang.String _reportType,
		java.lang.String _allowFg,
		java.lang.String _isActive,
		java.lang.String _name) {

		this.setId(_id);
		this.setIsMaster(_isMaster);
		this.setReportType(_reportType);
		this.setAllowFg(_allowFg);
		this.setIsActive(_isActive);
		this.setName(_name);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_TABLE_ID
	 */
	public java.lang.Integer getAdTableId () {
		return _adTableId;
	}

	/**
	 * Set the value related to the column: AD_TABLE_ID
	 * @param _adTableId the AD_TABLE_ID value
	 */
	public void setAdTableId (java.lang.Integer _adTableId) {
		this._adTableId = _adTableId;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierid () {
		return _modifierid;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierid the MODIFIERID value
	 */
	public void setModifierid (java.lang.Integer _modifierid) {
		this._modifierid = _modifierid;
	}


	/**
	 * Return the value associated with the column: AUTO_UPDATE
	 */
	public java.lang.String getAutoUpdate () {
		return _autoUpdate;
	}

	/**
	 * Set the value related to the column: AUTO_UPDATE
	 * @param _autoUpdate the AUTO_UPDATE value
	 */
	public void setAutoUpdate (java.lang.String _autoUpdate) {
		this._autoUpdate = _autoUpdate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISMASTER
	 */
	public java.lang.String getIsMaster () {
		return _isMaster;
	}

	/**
	 * Set the value related to the column: ISMASTER
	 * @param _isMaster the ISMASTER value
	 */
	public void setIsMaster (java.lang.String _isMaster) {
		this._isMaster = _isMaster;
	}


	/**
	 * Return the value associated with the column: REPORTTYPE
	 */
	public java.lang.String getReportType () {
		return _reportType;
	}

	/**
	 * Set the value related to the column: REPORTTYPE
	 * @param _reportType the REPORTTYPE value
	 */
	public void setReportType (java.lang.String _reportType) {
		this._reportType = _reportType;
	}


	/**
	 * Return the value associated with the column: ALLOW_FG
	 */
	public java.lang.String getAllowFg () {
		return _allowFg;
	}

	/**
	 * Set the value related to the column: ALLOW_FG
	 * @param _allowFg the ALLOW_FG value
	 */
	public void setAllowFg (java.lang.String _allowFg) {
		this._allowFg = _allowFg;
	}


	/**
	 * Return the value associated with the column: MASTER_TEMPLATE_ID
	 */
	public java.lang.Integer getMasterTemplateId () {
		return _masterTemplateId;
	}

	/**
	 * Set the value related to the column: MASTER_TEMPLATE_ID
	 * @param _masterTemplateId the MASTER_TEMPLATE_ID value
	 */
	public void setMasterTemplateId (java.lang.Integer _masterTemplateId) {
		this._masterTemplateId = _masterTemplateId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
	 * Return the value associated with the column: FILEURL
	 */
	public java.lang.String getFileUrl () {
		return _fileUrl;
	}

	/**
	 * Set the value related to the column: FILEURL
	 * @param _fileUrl the FILEURL value
	 */
	public void setFileUrl (java.lang.String _fileUrl) {
		this._fileUrl = _fileUrl;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: NAME
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: NAME
	 * @param _name the NAME value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: PREVIEWURL
	 */
	public java.lang.String getPreviewUrl () {
		return _previewUrl;
	}

	/**
	 * Set the value related to the column: PREVIEWURL
	 * @param _previewUrl the PREVIEWURL value
	 */
	public void setPreviewUrl (java.lang.String _previewUrl) {
		this._previewUrl = _previewUrl;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseAdReport)) return false;
		else {
			nds.model.base.BaseAdReport mObj = (nds.model.base.BaseAdReport) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}