package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the C_PAYMENT table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="C_PAYMENT"
 */
public abstract class BaseCPayment  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_TOT_DIFF_AMT = "TotDiffAmt";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_C_INVOICE = "CInvoice";
	public static String PROP_DATE_LAST_PAYMENT = "DateLastPayment";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_DATE_LAST_INOUT = "DateLastInout";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_DOCNO = "Docno";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_C_ORDER = "COrder";
	public static String PROP_DOC_TYPE = "DocType";
	public static String PROP_TOT_TARGET_AMT = "TotTargetAmt";
	public static String PROP_C_BPARTNER_ID = "CBpartnerId";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_TARGETDOC_TYPE = "TargetdocType";
	public static String PROP_M_INOUT = "MInout";
	public static String PROP_SALESREP_ID = "SalesrepId";
	public static String PROP_TOT_AMT = "TotAmt";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_SALESREP = "Salesrep";
	public static String PROP_M_INOUT_ID = "MInoutId";
	public static String PROP_C_BPARTNER = "CBpartner";
	public static String PROP_DATE_LAST_ORDER = "DateLastOrder";
	public static String PROP_C_INVOICE_ID = "CInvoiceId";
	public static String PROP_DATE_LAST_INVOICE = "DateLastInvoice";
	public static String PROP_TOT_LINES = "TotLines";
	public static String PROP_ID = "Id";
	public static String PROP_C_ORDER_ID = "COrderId";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _docno;
	private java.lang.String _docType;
	private java.lang.String _targetdocType;
	private java.lang.String _description;
	private java.lang.Integer _salesrepId;
	private java.util.Date _dateLastPayment;
	private java.util.Date _dateLastOrder;
	private java.util.Date _dateLastInout;
	private java.util.Date _dateLastInvoice;
	private java.lang.Integer _cBpartnerId;
	private java.lang.Integer _totTargetAmt;
	private double _totAmt;
	private double _totDiffAmt;
	private double _totLines;
	private java.lang.Integer _cOrderId;
	private java.lang.Integer _cInvoiceId;
	private java.lang.Integer _mInoutId;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;
	private java.lang.Integer _status;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.Users _salesrep;
	private nds.model.CBpartner _cBpartner;
	private nds.model.COrder _cOrder;
	private nds.model.CInvoice _cInvoice;
	private nds.model.MInout _mInout;


	// constructors
	public BaseCPayment () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCPayment (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCPayment (
		java.lang.Integer _id,
		java.lang.String _docno,
		java.lang.String _docType,
		java.lang.String _targetdocType,
		java.lang.String _description,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setDocno(_docno);
		this.setDocType(_docType);
		this.setTargetdocType(_targetdocType);
		this.setDescription(_description);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: DOCNO
	 */
	public java.lang.String getDocno () {
		return _docno;
	}

	/**
	 * Set the value related to the column: DOCNO
	 * @param _docno the DOCNO value
	 */
	public void setDocno (java.lang.String _docno) {
		this._docno = _docno;
	}


	/**
	 * Return the value associated with the column: DOCTYPE
	 */
	public java.lang.String getDocType () {
		return _docType;
	}

	/**
	 * Set the value related to the column: DOCTYPE
	 * @param _docType the DOCTYPE value
	 */
	public void setDocType (java.lang.String _docType) {
		this._docType = _docType;
	}


	/**
	 * Return the value associated with the column: TARGETDOCTYPE
	 */
	public java.lang.String getTargetdocType () {
		return _targetdocType;
	}

	/**
	 * Set the value related to the column: TARGETDOCTYPE
	 * @param _targetdocType the TARGETDOCTYPE value
	 */
	public void setTargetdocType (java.lang.String _targetdocType) {
		this._targetdocType = _targetdocType;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: SALESREP_ID
	 */
	public java.lang.Integer getSalesrepId () {
		return _salesrepId;
	}

	/**
	 * Set the value related to the column: SALESREP_ID
	 * @param _salesrepId the SALESREP_ID value
	 */
	public void setSalesrepId (java.lang.Integer _salesrepId) {
		this._salesrepId = _salesrepId;
	}


	/**
	 * Return the value associated with the column: DATE_LAST_PAYMENT
	 */
	public java.util.Date getDateLastPayment () {
		return _dateLastPayment;
	}

	/**
	 * Set the value related to the column: DATE_LAST_PAYMENT
	 * @param _dateLastPayment the DATE_LAST_PAYMENT value
	 */
	public void setDateLastPayment (java.util.Date _dateLastPayment) {
		this._dateLastPayment = _dateLastPayment;
	}


	/**
	 * Return the value associated with the column: DATE_LAST_ORDER
	 */
	public java.util.Date getDateLastOrder () {
		return _dateLastOrder;
	}

	/**
	 * Set the value related to the column: DATE_LAST_ORDER
	 * @param _dateLastOrder the DATE_LAST_ORDER value
	 */
	public void setDateLastOrder (java.util.Date _dateLastOrder) {
		this._dateLastOrder = _dateLastOrder;
	}


	/**
	 * Return the value associated with the column: DATE_LAST_INOUT
	 */
	public java.util.Date getDateLastInout () {
		return _dateLastInout;
	}

	/**
	 * Set the value related to the column: DATE_LAST_INOUT
	 * @param _dateLastInout the DATE_LAST_INOUT value
	 */
	public void setDateLastInout (java.util.Date _dateLastInout) {
		this._dateLastInout = _dateLastInout;
	}


	/**
	 * Return the value associated with the column: DATE_LAST_INVOICE
	 */
	public java.util.Date getDateLastInvoice () {
		return _dateLastInvoice;
	}

	/**
	 * Set the value related to the column: DATE_LAST_INVOICE
	 * @param _dateLastInvoice the DATE_LAST_INVOICE value
	 */
	public void setDateLastInvoice (java.util.Date _dateLastInvoice) {
		this._dateLastInvoice = _dateLastInvoice;
	}


	/**
	 * Return the value associated with the column: C_BPARTNER_ID
	 */
	public java.lang.Integer getCBpartnerId () {
		return _cBpartnerId;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartnerId the C_BPARTNER_ID value
	 */
	public void setCBpartnerId (java.lang.Integer _cBpartnerId) {
		this._cBpartnerId = _cBpartnerId;
	}


	/**
	 * Return the value associated with the column: TOT_TARGET_AMT
	 */
	public java.lang.Integer getTotTargetAmt () {
		return _totTargetAmt;
	}

	/**
	 * Set the value related to the column: TOT_TARGET_AMT
	 * @param _totTargetAmt the TOT_TARGET_AMT value
	 */
	public void setTotTargetAmt (java.lang.Integer _totTargetAmt) {
		this._totTargetAmt = _totTargetAmt;
	}


	/**
	 * Return the value associated with the column: TOT_AMT
	 */
	public double getTotAmt () {
		return _totAmt;
	}

	/**
	 * Set the value related to the column: TOT_AMT
	 * @param _totAmt the TOT_AMT value
	 */
	public void setTotAmt (double _totAmt) {
		this._totAmt = _totAmt;
	}


	/**
	 * Return the value associated with the column: TOT_DIFF_AMT
	 */
	public double getTotDiffAmt () {
		return _totDiffAmt;
	}

	/**
	 * Set the value related to the column: TOT_DIFF_AMT
	 * @param _totDiffAmt the TOT_DIFF_AMT value
	 */
	public void setTotDiffAmt (double _totDiffAmt) {
		this._totDiffAmt = _totDiffAmt;
	}


	/**
	 * Return the value associated with the column: TOT_LINES
	 */
	public double getTotLines () {
		return _totLines;
	}

	/**
	 * Set the value related to the column: TOT_LINES
	 * @param _totLines the TOT_LINES value
	 */
	public void setTotLines (double _totLines) {
		this._totLines = _totLines;
	}


	/**
	 * Return the value associated with the column: C_ORDER_ID
	 */
	public java.lang.Integer getCOrderId () {
		return _cOrderId;
	}

	/**
	 * Set the value related to the column: C_ORDER_ID
	 * @param _cOrderId the C_ORDER_ID value
	 */
	public void setCOrderId (java.lang.Integer _cOrderId) {
		this._cOrderId = _cOrderId;
	}


	/**
	 * Return the value associated with the column: C_INVOICE_ID
	 */
	public java.lang.Integer getCInvoiceId () {
		return _cInvoiceId;
	}

	/**
	 * Set the value related to the column: C_INVOICE_ID
	 * @param _cInvoiceId the C_INVOICE_ID value
	 */
	public void setCInvoiceId (java.lang.Integer _cInvoiceId) {
		this._cInvoiceId = _cInvoiceId;
	}


	/**
	 * Return the value associated with the column: M_INOUT_ID
	 */
	public java.lang.Integer getMInoutId () {
		return _mInoutId;
	}

	/**
	 * Set the value related to the column: M_INOUT_ID
	 * @param _mInoutId the M_INOUT_ID value
	 */
	public void setMInoutId (java.lang.Integer _mInoutId) {
		this._mInoutId = _mInoutId;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=SALESREP_ID
	 */
	public nds.model.Users getSalesrep () {
		return this._salesrep;
	}

	/**
	 * Set the value related to the column: SALESREP_ID
	 * @param _salesrep the SALESREP_ID value
	 */
	public void setSalesrep (nds.model.Users _salesrep) {
		this._salesrep = _salesrep;
	}


	/**
     * @hibernate.property
     *  column=C_BPARTNER_ID
	 */
	public nds.model.CBpartner getCBpartner () {
		return this._cBpartner;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartner the C_BPARTNER_ID value
	 */
	public void setCBpartner (nds.model.CBpartner _cBpartner) {
		this._cBpartner = _cBpartner;
	}


	/**
     * @hibernate.property
     *  column=C_ORDER_ID
	 */
	public nds.model.COrder getCOrder () {
		return this._cOrder;
	}

	/**
	 * Set the value related to the column: C_ORDER_ID
	 * @param _cOrder the C_ORDER_ID value
	 */
	public void setCOrder (nds.model.COrder _cOrder) {
		this._cOrder = _cOrder;
	}


	/**
     * @hibernate.property
     *  column=C_INVOICE_ID
	 */
	public nds.model.CInvoice getCInvoice () {
		return this._cInvoice;
	}

	/**
	 * Set the value related to the column: C_INVOICE_ID
	 * @param _cInvoice the C_INVOICE_ID value
	 */
	public void setCInvoice (nds.model.CInvoice _cInvoice) {
		this._cInvoice = _cInvoice;
	}


	/**
     * @hibernate.property
     *  column=M_INOUT_ID
	 */
	public nds.model.MInout getMInout () {
		return this._mInout;
	}

	/**
	 * Set the value related to the column: M_INOUT_ID
	 * @param _mInout the M_INOUT_ID value
	 */
	public void setMInout (nds.model.MInout _mInout) {
		this._mInout = _mInout;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseCPayment)) return false;
		else {
			nds.model.base.BaseCPayment mObj = (nds.model.base.BaseCPayment) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}