package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the C_INVOICE table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="C_INVOICE"
 */
public abstract class BaseCInvoice  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_C_PAYMENT_ID = "CPaymentId";
	public static String PROP_C_CURRENCY_ID = "CCurrencyId";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_PAYMENT_RULE = "PaymentRule";
	public static String PROP_DATE_ACCT = "DateAcct";
	public static String PROP_GRANDTOTAL = "Grandtotal";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_DOCNO = "Docno";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_C_ORDER = "COrder";
	public static String PROP_DOC_TYPE = "DocType";
	public static String PROP_C_BPARTNER_ID = "CBpartnerId";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_TARGETDOC_TYPE = "TargetdocType";
	public static String PROP_C_CURRENCY = "CCurrency";
	public static String PROP_C_BPARTNER_LOCATION_ID = "CBpartnerLocationId";
	public static String PROP_SALESREP_ID = "SalesrepId";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_C_PAYMENT = "CPayment";
	public static String PROP_REF_INVOICE_ID = "RefInvoiceId";
	public static String PROP_SALESREP = "Salesrep";
	public static String PROP_DATE_INVOICED = "DateInvoiced";
	public static String PROP_C_BPARTNER = "CBpartner";
	public static String PROP_TOT_TAX_AMT = "TotTaxAmt";
	public static String PROP_C_BPARTNER_LOCATION = "CBpartnerLocation";
	public static String PROP_DATE_ORDERED = "DateOrdered";
	public static String PROP_TOTALLINES = "Totallines";
	public static String PROP_REF_INVOICE = "RefInvoice";
	public static String PROP_ID = "Id";
	public static String PROP_C_ORDER_ID = "COrderId";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _docno;
	private java.lang.String _docType;
	private java.lang.String _targetdocType;
	private java.lang.Integer _cOrderId;
	private java.lang.String _description;
	private java.lang.Integer _salesrepId;
	private java.util.Date _dateInvoiced;
	private java.util.Date _dateAcct;
	private java.util.Date _dateOrdered;
	private java.lang.Integer _cBpartnerId;
	private java.lang.Integer _cBpartnerLocationId;
	private java.lang.Integer _cCurrencyId;
	private java.lang.String _paymentRule;
	private java.lang.Integer _totallines;
	private double _grandtotal;
	private double _totTaxAmt;
	private java.lang.Integer _cPaymentId;
	private java.lang.Integer _refInvoiceId;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;
	private java.lang.Integer _status;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.COrder _cOrder;
	private nds.model.Users _salesrep;
	private nds.model.CBpartner _cBpartner;
	private nds.model.CBpartnerLocation _cBpartnerLocation;
	private nds.model.CCurrency _cCurrency;
	private nds.model.CPayment _cPayment;
	private nds.model.CInvoice _refInvoice;


	// constructors
	public BaseCInvoice () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCInvoice (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCInvoice (
		java.lang.Integer _id,
		java.lang.String _docno,
		java.lang.String _docType,
		java.lang.String _targetdocType,
		java.lang.String _description,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setDocno(_docno);
		this.setDocType(_docType);
		this.setTargetdocType(_targetdocType);
		this.setDescription(_description);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: DOCNO
	 */
	public java.lang.String getDocno () {
		return _docno;
	}

	/**
	 * Set the value related to the column: DOCNO
	 * @param _docno the DOCNO value
	 */
	public void setDocno (java.lang.String _docno) {
		this._docno = _docno;
	}


	/**
	 * Return the value associated with the column: DOCTYPE
	 */
	public java.lang.String getDocType () {
		return _docType;
	}

	/**
	 * Set the value related to the column: DOCTYPE
	 * @param _docType the DOCTYPE value
	 */
	public void setDocType (java.lang.String _docType) {
		this._docType = _docType;
	}


	/**
	 * Return the value associated with the column: TARGETDOCTYPE
	 */
	public java.lang.String getTargetdocType () {
		return _targetdocType;
	}

	/**
	 * Set the value related to the column: TARGETDOCTYPE
	 * @param _targetdocType the TARGETDOCTYPE value
	 */
	public void setTargetdocType (java.lang.String _targetdocType) {
		this._targetdocType = _targetdocType;
	}


	/**
	 * Return the value associated with the column: C_ORDER_ID
	 */
	public java.lang.Integer getCOrderId () {
		return _cOrderId;
	}

	/**
	 * Set the value related to the column: C_ORDER_ID
	 * @param _cOrderId the C_ORDER_ID value
	 */
	public void setCOrderId (java.lang.Integer _cOrderId) {
		this._cOrderId = _cOrderId;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: SALESREP_ID
	 */
	public java.lang.Integer getSalesrepId () {
		return _salesrepId;
	}

	/**
	 * Set the value related to the column: SALESREP_ID
	 * @param _salesrepId the SALESREP_ID value
	 */
	public void setSalesrepId (java.lang.Integer _salesrepId) {
		this._salesrepId = _salesrepId;
	}


	/**
	 * Return the value associated with the column: DATEINVOICED
	 */
	public java.util.Date getDateInvoiced () {
		return _dateInvoiced;
	}

	/**
	 * Set the value related to the column: DATEINVOICED
	 * @param _dateInvoiced the DATEINVOICED value
	 */
	public void setDateInvoiced (java.util.Date _dateInvoiced) {
		this._dateInvoiced = _dateInvoiced;
	}


	/**
	 * Return the value associated with the column: DATEACCT
	 */
	public java.util.Date getDateAcct () {
		return _dateAcct;
	}

	/**
	 * Set the value related to the column: DATEACCT
	 * @param _dateAcct the DATEACCT value
	 */
	public void setDateAcct (java.util.Date _dateAcct) {
		this._dateAcct = _dateAcct;
	}


	/**
	 * Return the value associated with the column: DATEORDERED
	 */
	public java.util.Date getDateOrdered () {
		return _dateOrdered;
	}

	/**
	 * Set the value related to the column: DATEORDERED
	 * @param _dateOrdered the DATEORDERED value
	 */
	public void setDateOrdered (java.util.Date _dateOrdered) {
		this._dateOrdered = _dateOrdered;
	}


	/**
	 * Return the value associated with the column: C_BPARTNER_ID
	 */
	public java.lang.Integer getCBpartnerId () {
		return _cBpartnerId;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartnerId the C_BPARTNER_ID value
	 */
	public void setCBpartnerId (java.lang.Integer _cBpartnerId) {
		this._cBpartnerId = _cBpartnerId;
	}


	/**
	 * Return the value associated with the column: C_BPARTNER_LOCATION_ID
	 */
	public java.lang.Integer getCBpartnerLocationId () {
		return _cBpartnerLocationId;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_LOCATION_ID
	 * @param _cBpartnerLocationId the C_BPARTNER_LOCATION_ID value
	 */
	public void setCBpartnerLocationId (java.lang.Integer _cBpartnerLocationId) {
		this._cBpartnerLocationId = _cBpartnerLocationId;
	}


	/**
	 * Return the value associated with the column: C_CURRENCY_ID
	 */
	public java.lang.Integer getCCurrencyId () {
		return _cCurrencyId;
	}

	/**
	 * Set the value related to the column: C_CURRENCY_ID
	 * @param _cCurrencyId the C_CURRENCY_ID value
	 */
	public void setCCurrencyId (java.lang.Integer _cCurrencyId) {
		this._cCurrencyId = _cCurrencyId;
	}


	/**
	 * Return the value associated with the column: PAYMENTRULE
	 */
	public java.lang.String getPaymentRule () {
		return _paymentRule;
	}

	/**
	 * Set the value related to the column: PAYMENTRULE
	 * @param _paymentRule the PAYMENTRULE value
	 */
	public void setPaymentRule (java.lang.String _paymentRule) {
		this._paymentRule = _paymentRule;
	}


	/**
	 * Return the value associated with the column: TOTALLINES
	 */
	public java.lang.Integer getTotallines () {
		return _totallines;
	}

	/**
	 * Set the value related to the column: TOTALLINES
	 * @param _totallines the TOTALLINES value
	 */
	public void setTotallines (java.lang.Integer _totallines) {
		this._totallines = _totallines;
	}


	/**
	 * Return the value associated with the column: GRANDTOTAL
	 */
	public double getGrandtotal () {
		return _grandtotal;
	}

	/**
	 * Set the value related to the column: GRANDTOTAL
	 * @param _grandtotal the GRANDTOTAL value
	 */
	public void setGrandtotal (double _grandtotal) {
		this._grandtotal = _grandtotal;
	}


	/**
	 * Return the value associated with the column: TOT_TAXAMT
	 */
	public double getTotTaxAmt () {
		return _totTaxAmt;
	}

	/**
	 * Set the value related to the column: TOT_TAXAMT
	 * @param _totTaxAmt the TOT_TAXAMT value
	 */
	public void setTotTaxAmt (double _totTaxAmt) {
		this._totTaxAmt = _totTaxAmt;
	}


	/**
	 * Return the value associated with the column: C_PAYMENT_ID
	 */
	public java.lang.Integer getCPaymentId () {
		return _cPaymentId;
	}

	/**
	 * Set the value related to the column: C_PAYMENT_ID
	 * @param _cPaymentId the C_PAYMENT_ID value
	 */
	public void setCPaymentId (java.lang.Integer _cPaymentId) {
		this._cPaymentId = _cPaymentId;
	}


	/**
	 * Return the value associated with the column: REF_INVOICE_ID
	 */
	public java.lang.Integer getRefInvoiceId () {
		return _refInvoiceId;
	}

	/**
	 * Set the value related to the column: REF_INVOICE_ID
	 * @param _refInvoiceId the REF_INVOICE_ID value
	 */
	public void setRefInvoiceId (java.lang.Integer _refInvoiceId) {
		this._refInvoiceId = _refInvoiceId;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=C_ORDER_ID
	 */
	public nds.model.COrder getCOrder () {
		return this._cOrder;
	}

	/**
	 * Set the value related to the column: C_ORDER_ID
	 * @param _cOrder the C_ORDER_ID value
	 */
	public void setCOrder (nds.model.COrder _cOrder) {
		this._cOrder = _cOrder;
	}


	/**
     * @hibernate.property
     *  column=SALESREP_ID
	 */
	public nds.model.Users getSalesrep () {
		return this._salesrep;
	}

	/**
	 * Set the value related to the column: SALESREP_ID
	 * @param _salesrep the SALESREP_ID value
	 */
	public void setSalesrep (nds.model.Users _salesrep) {
		this._salesrep = _salesrep;
	}


	/**
     * @hibernate.property
     *  column=C_BPARTNER_ID
	 */
	public nds.model.CBpartner getCBpartner () {
		return this._cBpartner;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartner the C_BPARTNER_ID value
	 */
	public void setCBpartner (nds.model.CBpartner _cBpartner) {
		this._cBpartner = _cBpartner;
	}


	/**
     * @hibernate.property
     *  column=C_BPARTNER_LOCATION_ID
	 */
	public nds.model.CBpartnerLocation getCBpartnerLocation () {
		return this._cBpartnerLocation;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_LOCATION_ID
	 * @param _cBpartnerLocation the C_BPARTNER_LOCATION_ID value
	 */
	public void setCBpartnerLocation (nds.model.CBpartnerLocation _cBpartnerLocation) {
		this._cBpartnerLocation = _cBpartnerLocation;
	}


	/**
     * @hibernate.property
     *  column=C_CURRENCY_ID
	 */
	public nds.model.CCurrency getCCurrency () {
		return this._cCurrency;
	}

	/**
	 * Set the value related to the column: C_CURRENCY_ID
	 * @param _cCurrency the C_CURRENCY_ID value
	 */
	public void setCCurrency (nds.model.CCurrency _cCurrency) {
		this._cCurrency = _cCurrency;
	}


	/**
     * @hibernate.property
     *  column=C_PAYMENT_ID
	 */
	public nds.model.CPayment getCPayment () {
		return this._cPayment;
	}

	/**
	 * Set the value related to the column: C_PAYMENT_ID
	 * @param _cPayment the C_PAYMENT_ID value
	 */
	public void setCPayment (nds.model.CPayment _cPayment) {
		this._cPayment = _cPayment;
	}


	/**
     * @hibernate.property
     *  column=REF_INVOICE_ID
	 */
	public nds.model.CInvoice getRefInvoice () {
		return this._refInvoice;
	}

	/**
	 * Set the value related to the column: REF_INVOICE_ID
	 * @param _refInvoice the REF_INVOICE_ID value
	 */
	public void setRefInvoice (nds.model.CInvoice _refInvoice) {
		this._refInvoice = _refInvoice;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseCInvoice)) return false;
		else {
			nds.model.base.BaseCInvoice mObj = (nds.model.base.BaseCInvoice) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}