package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the AD_Query table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="AD_Query"
 */
public abstract class BaseAdQuery  implements Serializable {

	public static String PROP_QUERY = "Query";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_AD_CUBE_ID = "AdCubeId";
	public static String PROP_NAME = "Name";
	public static String PROP_ID = "Id";
	public static String PROP_QUERY_PARAM = "QueryParam";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.String _name;
	private java.lang.String _query;
	private java.lang.String _queryParam;
	private java.lang.String _isActive;
	private java.lang.Integer _adCubeId;


	// constructors
	public BaseAdQuery () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAdQuery (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAdQuery (
		java.lang.Integer _id,
		java.lang.String _name,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setName(_name);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="assigned"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: NAME
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: NAME
	 * @param _name the NAME value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: QUERY
	 */
	public java.lang.String getQuery () {
		return _query;
	}

	/**
	 * Set the value related to the column: QUERY
	 * @param _query the QUERY value
	 */
	public void setQuery (java.lang.String _query) {
		this._query = _query;
	}


	/**
	 * Return the value associated with the column: QUERYPARAM
	 */
	public java.lang.String getQueryParam () {
		return _queryParam;
	}

	/**
	 * Set the value related to the column: QUERYPARAM
	 * @param _queryParam the QUERYPARAM value
	 */
	public void setQueryParam (java.lang.String _queryParam) {
		this._queryParam = _queryParam;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
	 * Return the value associated with the column: AD_CUBE_ID
	 */
	public java.lang.Integer getAdCubeId () {
		return _adCubeId;
	}

	/**
	 * Set the value related to the column: AD_CUBE_ID
	 * @param _adCubeId the AD_CUBE_ID value
	 */
	public void setAdCubeId (java.lang.Integer _adCubeId) {
		this._adCubeId = _adCubeId;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseAdQuery)) return false;
		else {
			nds.model.base.BaseAdQuery mObj = (nds.model.base.BaseAdQuery) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}