package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the U_CLOB table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="U_CLOB"
 */
public abstract class BaseUClob  implements Serializable {

	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_REF_OBJECT_ID = "RefObjectId";
	public static String PROP_REF_U_R_L = "RefURL";
	public static String PROP_REF_TABLE = "RefTable";
	public static String PROP_MODIFIEDDATE = "Modifieddate";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_MODIFIERID = "Modifierid";
	public static String PROP_NAME = "Name";
	public static String PROP_CONTENT = "Content";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _modifierid;
	private java.util.Date _modifieddate;
	private java.lang.Integer _adOrgId;
	private java.lang.String _isActive;
	private java.lang.Integer _refObjectId;
	private java.lang.String _refURL;
	private java.lang.Integer _ownerId;
	private java.util.Date _creationDate;
	private java.lang.String _name;
	private java.sql.Clob _content;
	private java.lang.String _refTable;


	// constructors
	public BaseUClob () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUClob (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierid () {
		return _modifierid;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierid the MODIFIERID value
	 */
	public void setModifierid (java.lang.Integer _modifierid) {
		this._modifierid = _modifierid;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifieddate () {
		return _modifieddate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifieddate the MODIFIEDDATE value
	 */
	public void setModifieddate (java.util.Date _modifieddate) {
		this._modifieddate = _modifieddate;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
	 * Return the value associated with the column: REFOBJECT_ID
	 */
	public java.lang.Integer getRefObjectId () {
		return _refObjectId;
	}

	/**
	 * Set the value related to the column: REFOBJECT_ID
	 * @param _refObjectId the REFOBJECT_ID value
	 */
	public void setRefObjectId (java.lang.Integer _refObjectId) {
		this._refObjectId = _refObjectId;
	}


	/**
	 * Return the value associated with the column: REFURL
	 */
	public java.lang.String getRefURL () {
		return _refURL;
	}

	/**
	 * Set the value related to the column: REFURL
	 * @param _refURL the REFURL value
	 */
	public void setRefURL (java.lang.String _refURL) {
		this._refURL = _refURL;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: NAME
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: NAME
	 * @param _name the NAME value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: CONTENT
	 */
	public java.sql.Clob getContent () {
		return _content;
	}

	/**
	 * Set the value related to the column: CONTENT
	 * @param _content the CONTENT value
	 */
	public void setContent (java.sql.Clob _content) {
		this._content = _content;
	}


	/**
	 * Return the value associated with the column: REFTABLE
	 */
	public java.lang.String getRefTable () {
		return _refTable;
	}

	/**
	 * Set the value related to the column: REFTABLE
	 * @param _refTable the REFTABLE value
	 */
	public void setRefTable (java.lang.String _refTable) {
		this._refTable = _refTable;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseUClob)) return false;
		else {
			nds.model.base.BaseUClob mObj = (nds.model.base.BaseUClob) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}