package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the C_UOM_CONVERSION table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="C_UOM_CONVERSION"
 */
public abstract class BaseCUomConversion  implements Serializable {

	public static String PROP_M_PRODUCT_ID = "MProductId";
	public static String PROP_C_UOM_TO_ID = "CUomToId";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_M_PRODUCT = "MProduct";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_C_UOM = "CUom";
	public static String PROP_MULTIPLYRATE = "Multiplyrate";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_C_UOM_TO = "CUomTo";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_C_UOM_ID = "CUomId";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.Integer _mProductId;
	private java.lang.Integer _cUomId;
	private java.lang.Integer _cUomToId;
	private double _multiplyrate;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.MProduct _mProduct;
	private nds.model.CUom _cUom;
	private nds.model.CUom _cUomTo;


	// constructors
	public BaseCUomConversion () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCUomConversion (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCUomConversion (
		java.lang.Integer _id,
		double _multiplyrate,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setMultiplyrate(_multiplyrate);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: M_PRODUCT_ID
	 */
	public java.lang.Integer getMProductId () {
		return _mProductId;
	}

	/**
	 * Set the value related to the column: M_PRODUCT_ID
	 * @param _mProductId the M_PRODUCT_ID value
	 */
	public void setMProductId (java.lang.Integer _mProductId) {
		this._mProductId = _mProductId;
	}


	/**
	 * Return the value associated with the column: C_UOM_ID
	 */
	public java.lang.Integer getCUomId () {
		return _cUomId;
	}

	/**
	 * Set the value related to the column: C_UOM_ID
	 * @param _cUomId the C_UOM_ID value
	 */
	public void setCUomId (java.lang.Integer _cUomId) {
		this._cUomId = _cUomId;
	}


	/**
	 * Return the value associated with the column: C_UOM_TO_ID
	 */
	public java.lang.Integer getCUomToId () {
		return _cUomToId;
	}

	/**
	 * Set the value related to the column: C_UOM_TO_ID
	 * @param _cUomToId the C_UOM_TO_ID value
	 */
	public void setCUomToId (java.lang.Integer _cUomToId) {
		this._cUomToId = _cUomToId;
	}


	/**
	 * Return the value associated with the column: MULTIPLYRATE
	 */
	public double getMultiplyrate () {
		return _multiplyrate;
	}

	/**
	 * Set the value related to the column: MULTIPLYRATE
	 * @param _multiplyrate the MULTIPLYRATE value
	 */
	public void setMultiplyrate (double _multiplyrate) {
		this._multiplyrate = _multiplyrate;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=M_PRODUCT_ID
	 */
	public nds.model.MProduct getMProduct () {
		return this._mProduct;
	}

	/**
	 * Set the value related to the column: M_PRODUCT_ID
	 * @param _mProduct the M_PRODUCT_ID value
	 */
	public void setMProduct (nds.model.MProduct _mProduct) {
		this._mProduct = _mProduct;
	}


	/**
     * @hibernate.property
     *  column=C_UOM_ID
	 */
	public nds.model.CUom getCUom () {
		return this._cUom;
	}

	/**
	 * Set the value related to the column: C_UOM_ID
	 * @param _cUom the C_UOM_ID value
	 */
	public void setCUom (nds.model.CUom _cUom) {
		this._cUom = _cUom;
	}


	/**
     * @hibernate.property
     *  column=C_UOM_TO_ID
	 */
	public nds.model.CUom getCUomTo () {
		return this._cUomTo;
	}

	/**
	 * Set the value related to the column: C_UOM_TO_ID
	 * @param _cUomTo the C_UOM_TO_ID value
	 */
	public void setCUomTo (nds.model.CUom _cUomTo) {
		this._cUomTo = _cUomTo;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseCUomConversion)) return false;
		else {
			nds.model.base.BaseCUomConversion mObj = (nds.model.base.BaseCUomConversion) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}