package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the C_INVOICEITEM table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="C_INVOICEITEM"
 */
public abstract class BaseCInvoiceItem  implements Serializable {

	public static String PROP_M_PRODUCT_ID = "MProductId";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_M_PRODUCT = "MProduct";
	public static String PROP_C_UOM = "CUom";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_C_INVOICE = "CInvoice";
	public static String PROP_LINETOTAL_AMT = "LinetotalAmt";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_LINE = "Line";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_M_ATTRIBUTE_SET_INSTANCE_ID = "MAttributeSetInstanceId";
	public static String PROP_C_UOM_ID = "CUomId";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_C_TAX_ID = "CTaxId";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_QTYINVOICED = "Qtyinvoiced";
	public static String PROP_REF_INVOICE_ITEM_ID = "RefInvoiceItemId";
	public static String PROP_TAX_AMT = "TaxAmt";
	public static String PROP_M_ATTRIBUTE_SET_INSTANCE = "MAttributeSetInstance";
	public static String PROP_C_TAX = "CTax";
	public static String PROP_PRICELIST = "Pricelist";
	public static String PROP_REF_INVOICE_ITEM = "RefInvoiceItem";
	public static String PROP_PRICEACTUAL = "Priceactual";
	public static String PROP_C_INVOICE_ID = "CInvoiceId";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.Integer _cInvoiceId;
	private java.lang.Integer _line;
	private java.lang.String _description;
	private java.lang.Integer _mProductId;
	private java.lang.Integer _mAttributeSetInstanceId;
	private java.lang.Integer _cUomId;
	private java.lang.Integer _refInvoiceItemId;
	private java.lang.Integer _qtyinvoiced;
	private double _pricelist;
	private double _priceactual;
	private double _linetotalAmt;
	private java.lang.Integer _cTaxId;
	private double _taxAmt;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.CInvoice _cInvoice;
	private nds.model.MProduct _mProduct;
	private nds.model.MAttributeSetInstance _mAttributeSetInstance;
	private nds.model.CUom _cUom;
	private nds.model.CInvoiceItem _refInvoiceItem;
	private nds.model.CTax _cTax;


	// constructors
	public BaseCInvoiceItem () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCInvoiceItem (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCInvoiceItem (
		java.lang.Integer _id,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: C_INVOICE_ID
	 */
	public java.lang.Integer getCInvoiceId () {
		return _cInvoiceId;
	}

	/**
	 * Set the value related to the column: C_INVOICE_ID
	 * @param _cInvoiceId the C_INVOICE_ID value
	 */
	public void setCInvoiceId (java.lang.Integer _cInvoiceId) {
		this._cInvoiceId = _cInvoiceId;
	}


	/**
	 * Return the value associated with the column: LINE
	 */
	public java.lang.Integer getLine () {
		return _line;
	}

	/**
	 * Set the value related to the column: LINE
	 * @param _line the LINE value
	 */
	public void setLine (java.lang.Integer _line) {
		this._line = _line;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: M_PRODUCT_ID
	 */
	public java.lang.Integer getMProductId () {
		return _mProductId;
	}

	/**
	 * Set the value related to the column: M_PRODUCT_ID
	 * @param _mProductId the M_PRODUCT_ID value
	 */
	public void setMProductId (java.lang.Integer _mProductId) {
		this._mProductId = _mProductId;
	}


	/**
	 * Return the value associated with the column: M_ATTRIBUTESETINSTANCE_ID
	 */
	public java.lang.Integer getMAttributeSetInstanceId () {
		return _mAttributeSetInstanceId;
	}

	/**
	 * Set the value related to the column: M_ATTRIBUTESETINSTANCE_ID
	 * @param _mAttributeSetInstanceId the M_ATTRIBUTESETINSTANCE_ID value
	 */
	public void setMAttributeSetInstanceId (java.lang.Integer _mAttributeSetInstanceId) {
		this._mAttributeSetInstanceId = _mAttributeSetInstanceId;
	}


	/**
	 * Return the value associated with the column: C_UOM_ID
	 */
	public java.lang.Integer getCUomId () {
		return _cUomId;
	}

	/**
	 * Set the value related to the column: C_UOM_ID
	 * @param _cUomId the C_UOM_ID value
	 */
	public void setCUomId (java.lang.Integer _cUomId) {
		this._cUomId = _cUomId;
	}


	/**
	 * Return the value associated with the column: REF_INVOICEITEM_ID
	 */
	public java.lang.Integer getRefInvoiceItemId () {
		return _refInvoiceItemId;
	}

	/**
	 * Set the value related to the column: REF_INVOICEITEM_ID
	 * @param _refInvoiceItemId the REF_INVOICEITEM_ID value
	 */
	public void setRefInvoiceItemId (java.lang.Integer _refInvoiceItemId) {
		this._refInvoiceItemId = _refInvoiceItemId;
	}


	/**
	 * Return the value associated with the column: QTYINVOICED
	 */
	public java.lang.Integer getQtyinvoiced () {
		return _qtyinvoiced;
	}

	/**
	 * Set the value related to the column: QTYINVOICED
	 * @param _qtyinvoiced the QTYINVOICED value
	 */
	public void setQtyinvoiced (java.lang.Integer _qtyinvoiced) {
		this._qtyinvoiced = _qtyinvoiced;
	}


	/**
	 * Return the value associated with the column: PRICELIST
	 */
	public double getPricelist () {
		return _pricelist;
	}

	/**
	 * Set the value related to the column: PRICELIST
	 * @param _pricelist the PRICELIST value
	 */
	public void setPricelist (double _pricelist) {
		this._pricelist = _pricelist;
	}


	/**
	 * Return the value associated with the column: PRICEACTUAL
	 */
	public double getPriceactual () {
		return _priceactual;
	}

	/**
	 * Set the value related to the column: PRICEACTUAL
	 * @param _priceactual the PRICEACTUAL value
	 */
	public void setPriceactual (double _priceactual) {
		this._priceactual = _priceactual;
	}


	/**
	 * Return the value associated with the column: LINETOTALAMT
	 */
	public double getLinetotalAmt () {
		return _linetotalAmt;
	}

	/**
	 * Set the value related to the column: LINETOTALAMT
	 * @param _linetotalAmt the LINETOTALAMT value
	 */
	public void setLinetotalAmt (double _linetotalAmt) {
		this._linetotalAmt = _linetotalAmt;
	}


	/**
	 * Return the value associated with the column: C_TAX_ID
	 */
	public java.lang.Integer getCTaxId () {
		return _cTaxId;
	}

	/**
	 * Set the value related to the column: C_TAX_ID
	 * @param _cTaxId the C_TAX_ID value
	 */
	public void setCTaxId (java.lang.Integer _cTaxId) {
		this._cTaxId = _cTaxId;
	}


	/**
	 * Return the value associated with the column: TAXAMT
	 */
	public double getTaxAmt () {
		return _taxAmt;
	}

	/**
	 * Set the value related to the column: TAXAMT
	 * @param _taxAmt the TAXAMT value
	 */
	public void setTaxAmt (double _taxAmt) {
		this._taxAmt = _taxAmt;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=C_INVOICE_ID
	 */
	public nds.model.CInvoice getCInvoice () {
		return this._cInvoice;
	}

	/**
	 * Set the value related to the column: C_INVOICE_ID
	 * @param _cInvoice the C_INVOICE_ID value
	 */
	public void setCInvoice (nds.model.CInvoice _cInvoice) {
		this._cInvoice = _cInvoice;
	}


	/**
     * @hibernate.property
     *  column=M_PRODUCT_ID
	 */
	public nds.model.MProduct getMProduct () {
		return this._mProduct;
	}

	/**
	 * Set the value related to the column: M_PRODUCT_ID
	 * @param _mProduct the M_PRODUCT_ID value
	 */
	public void setMProduct (nds.model.MProduct _mProduct) {
		this._mProduct = _mProduct;
	}


	/**
     * @hibernate.property
     *  column=M_ATTRIBUTESETINSTANCE_ID
	 */
	public nds.model.MAttributeSetInstance getMAttributeSetInstance () {
		return this._mAttributeSetInstance;
	}

	/**
	 * Set the value related to the column: M_ATTRIBUTESETINSTANCE_ID
	 * @param _mAttributeSetInstance the M_ATTRIBUTESETINSTANCE_ID value
	 */
	public void setMAttributeSetInstance (nds.model.MAttributeSetInstance _mAttributeSetInstance) {
		this._mAttributeSetInstance = _mAttributeSetInstance;
	}


	/**
     * @hibernate.property
     *  column=C_UOM_ID
	 */
	public nds.model.CUom getCUom () {
		return this._cUom;
	}

	/**
	 * Set the value related to the column: C_UOM_ID
	 * @param _cUom the C_UOM_ID value
	 */
	public void setCUom (nds.model.CUom _cUom) {
		this._cUom = _cUom;
	}


	/**
     * @hibernate.property
     *  column=REF_INVOICEITEM_ID
	 */
	public nds.model.CInvoiceItem getRefInvoiceItem () {
		return this._refInvoiceItem;
	}

	/**
	 * Set the value related to the column: REF_INVOICEITEM_ID
	 * @param _refInvoiceItem the REF_INVOICEITEM_ID value
	 */
	public void setRefInvoiceItem (nds.model.CInvoiceItem _refInvoiceItem) {
		this._refInvoiceItem = _refInvoiceItem;
	}


	/**
     * @hibernate.property
     *  column=C_TAX_ID
	 */
	public nds.model.CTax getCTax () {
		return this._cTax;
	}

	/**
	 * Set the value related to the column: C_TAX_ID
	 * @param _cTax the C_TAX_ID value
	 */
	public void setCTax (nds.model.CTax _cTax) {
		this._cTax = _cTax;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseCInvoiceItem)) return false;
		else {
			nds.model.base.BaseCInvoiceItem mObj = (nds.model.base.BaseCInvoiceItem) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}