package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the USERS table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="USERS"
 */
public abstract class BaseUsers  implements Serializable {

	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_BIRTHDAY = "Birthday";
	public static String PROP_PASSWORDHASH = "Passwordhash";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_LASTCONTACT = "Lastcontact";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_PASSWORD = "Password";
	public static String PROP_C_GREETING_ID = "CGreetingId";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_FAX = "Fax";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_SUPERVISOR_ID = "SupervisorId";
	public static String PROP_PHONE2 = "Phone2";
	public static String PROP_C_BPARTNER_ID = "CBpartnerId";
	public static String PROP_NAME = "Name";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_C_BPARTNER_LOCATION_ID = "CBpartnerLocationId";
	public static String PROP_LASTRESULT = "Lastresult";
	public static String PROP_IS_ADMIN = "IsAdmin";
	public static String PROP_IS_ENABLED = "IsEnabled";
	public static String PROP_PHONE = "Phone";
	public static String PROP_EMAIL = "Email";
	public static String PROP_COMMENTS = "Comments";
	public static String PROP_TITLE = "Title";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _name;
	private java.lang.Integer _isEnabled;
	private java.lang.Integer _isAdmin;
	private java.lang.String _passwordhash;
	private java.lang.String _password;
	private java.lang.String _email;
	private java.lang.String _description;
	private java.lang.Integer _cBpartnerId;
	private java.lang.Integer _cBpartnerLocationId;
	private java.lang.Integer _supervisorId;
	private java.lang.Integer _cGreetingId;
	private java.lang.String _title;
	private java.lang.String _comments;
	private java.lang.String _phone;
	private java.lang.String _phone2;
	private java.lang.String _fax;
	private java.util.Date _birthday;
	private java.util.Date _lastcontact;
	private java.lang.String _lastresult;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;


	// constructors
	public BaseUsers () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseUsers (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseUsers (
		java.lang.Integer _id,
		java.lang.String _name,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setName(_name);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="assigned"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: NAME
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: NAME
	 * @param _name the NAME value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: ISENABLED
	 */
	public java.lang.Integer getIsEnabled () {
		return _isEnabled;
	}

	/**
	 * Set the value related to the column: ISENABLED
	 * @param _isEnabled the ISENABLED value
	 */
	public void setIsEnabled (java.lang.Integer _isEnabled) {
		this._isEnabled = _isEnabled;
	}


	/**
	 * Return the value associated with the column: ISADMIN
	 */
	public java.lang.Integer getIsAdmin () {
		return _isAdmin;
	}

	/**
	 * Set the value related to the column: ISADMIN
	 * @param _isAdmin the ISADMIN value
	 */
	public void setIsAdmin (java.lang.Integer _isAdmin) {
		this._isAdmin = _isAdmin;
	}


	/**
	 * Return the value associated with the column: PASSWORDHASH
	 */
	public java.lang.String getPasswordhash () {
		return _passwordhash;
	}

	/**
	 * Set the value related to the column: PASSWORDHASH
	 * @param _passwordhash the PASSWORDHASH value
	 */
	public void setPasswordhash (java.lang.String _passwordhash) {
		this._passwordhash = _passwordhash;
	}


	/**
	 * Return the value associated with the column: PASSWORD
	 */
	public java.lang.String getPassword () {
		return _password;
	}

	/**
	 * Set the value related to the column: PASSWORD
	 * @param _password the PASSWORD value
	 */
	public void setPassword (java.lang.String _password) {
		this._password = _password;
	}


	/**
	 * Return the value associated with the column: EMAIL
	 */
	public java.lang.String getEmail () {
		return _email;
	}

	/**
	 * Set the value related to the column: EMAIL
	 * @param _email the EMAIL value
	 */
	public void setEmail (java.lang.String _email) {
		this._email = _email;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: C_BPARTNER_ID
	 */
	public java.lang.Integer getCBpartnerId () {
		return _cBpartnerId;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartnerId the C_BPARTNER_ID value
	 */
	public void setCBpartnerId (java.lang.Integer _cBpartnerId) {
		this._cBpartnerId = _cBpartnerId;
	}


	/**
	 * Return the value associated with the column: C_BPARTNER_LOCATION_ID
	 */
	public java.lang.Integer getCBpartnerLocationId () {
		return _cBpartnerLocationId;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_LOCATION_ID
	 * @param _cBpartnerLocationId the C_BPARTNER_LOCATION_ID value
	 */
	public void setCBpartnerLocationId (java.lang.Integer _cBpartnerLocationId) {
		this._cBpartnerLocationId = _cBpartnerLocationId;
	}


	/**
	 * Return the value associated with the column: SUPERVISOR_ID
	 */
	public java.lang.Integer getSupervisorId () {
		return _supervisorId;
	}

	/**
	 * Set the value related to the column: SUPERVISOR_ID
	 * @param _supervisorId the SUPERVISOR_ID value
	 */
	public void setSupervisorId (java.lang.Integer _supervisorId) {
		this._supervisorId = _supervisorId;
	}


	/**
	 * Return the value associated with the column: C_GREETING_ID
	 */
	public java.lang.Integer getCGreetingId () {
		return _cGreetingId;
	}

	/**
	 * Set the value related to the column: C_GREETING_ID
	 * @param _cGreetingId the C_GREETING_ID value
	 */
	public void setCGreetingId (java.lang.Integer _cGreetingId) {
		this._cGreetingId = _cGreetingId;
	}


	/**
	 * Return the value associated with the column: TITLE
	 */
	public java.lang.String getTitle () {
		return _title;
	}

	/**
	 * Set the value related to the column: TITLE
	 * @param _title the TITLE value
	 */
	public void setTitle (java.lang.String _title) {
		this._title = _title;
	}


	/**
	 * Return the value associated with the column: COMMENTS
	 */
	public java.lang.String getComments () {
		return _comments;
	}

	/**
	 * Set the value related to the column: COMMENTS
	 * @param _comments the COMMENTS value
	 */
	public void setComments (java.lang.String _comments) {
		this._comments = _comments;
	}


	/**
	 * Return the value associated with the column: PHONE
	 */
	public java.lang.String getPhone () {
		return _phone;
	}

	/**
	 * Set the value related to the column: PHONE
	 * @param _phone the PHONE value
	 */
	public void setPhone (java.lang.String _phone) {
		this._phone = _phone;
	}


	/**
	 * Return the value associated with the column: PHONE2
	 */
	public java.lang.String getPhone2 () {
		return _phone2;
	}

	/**
	 * Set the value related to the column: PHONE2
	 * @param _phone2 the PHONE2 value
	 */
	public void setPhone2 (java.lang.String _phone2) {
		this._phone2 = _phone2;
	}


	/**
	 * Return the value associated with the column: FAX
	 */
	public java.lang.String getFax () {
		return _fax;
	}

	/**
	 * Set the value related to the column: FAX
	 * @param _fax the FAX value
	 */
	public void setFax (java.lang.String _fax) {
		this._fax = _fax;
	}


	/**
	 * Return the value associated with the column: BIRTHDAY
	 */
	public java.util.Date getBirthday () {
		return _birthday;
	}

	/**
	 * Set the value related to the column: BIRTHDAY
	 * @param _birthday the BIRTHDAY value
	 */
	public void setBirthday (java.util.Date _birthday) {
		this._birthday = _birthday;
	}


	/**
	 * Return the value associated with the column: LASTCONTACT
	 */
	public java.util.Date getLastcontact () {
		return _lastcontact;
	}

	/**
	 * Set the value related to the column: LASTCONTACT
	 * @param _lastcontact the LASTCONTACT value
	 */
	public void setLastcontact (java.util.Date _lastcontact) {
		this._lastcontact = _lastcontact;
	}


	/**
	 * Return the value associated with the column: LASTRESULT
	 */
	public java.lang.String getLastresult () {
		return _lastresult;
	}

	/**
	 * Set the value related to the column: LASTRESULT
	 * @param _lastresult the LASTRESULT value
	 */
	public void setLastresult (java.lang.String _lastresult) {
		this._lastresult = _lastresult;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseUsers)) return false;
		else {
			nds.model.base.BaseUsers mObj = (nds.model.base.BaseUsers) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}