package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the AD_TABLE table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="AD_TABLE"
 */
public abstract class BaseAdTable  implements Serializable {

	public static String PROP_PARENT_COLUMN_ID = "ParentColumnId";
	public static String PROP_HAS_TRIG_BD = "HasTrigBd";
	public static String PROP_PROC_SUBMIT = "ProcSubmit";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_MASK = "Mask";
	public static String PROP_FILTER = "Filter";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_IS_S_M_S = "IsSMS";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_TRIG_BM = "TrigBm";
	public static String PROP_AD_TABLE_CATEGORY = "AdTableCategory";
	public static String PROP_IS_BIG = "IsBig";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_ORDERNO = "Orderno";
	public static String PROP_TRIG_AM = "TrigAm";
	public static String PROP_NAME = "Name";
	public static String PROP_ALIASNAME = "AliasName";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_DIRECTORY_ID = "DirectoryId";
	public static String PROP_DK_COLUMN_ID = "DkColumnId";
	public static String PROP_REALTABLE = "Realtable";
	public static String PROP_AK_COLUMN_ID = "AkColumnId";
	public static String PROP_HAS_TRIG_AC = "HasTrigAc";
	public static String PROP_HAS_TRIG_BM = "HasTrigBm";
	public static String PROP_IS_DISPATCHABLE = "IsDispatchable";
	public static String PROP_AD_TABLE_CATEGORY_ID = "AdTableCategoryId";
	public static String PROP_U_CLOB_ID = "UClobId";
	public static String PROP_URL = "Url";
	public static String PROP_REALTABLE_ID = "RealtableId";
	public static String PROP_TRIG_AC = "TrigAc";
	public static String PROP_ROW_CNT = "RowCnt";
	public static String PROP_HAS_TRIG_AM = "HasTrigAm";
	public static String PROP_TRIG_BD = "TrigBd";
	public static String PROP_PK_COLUMN_ID = "PkColumnId";
	public static String PROP_IS_MENU_OBJ = "IsMenuObj";
	public static String PROP_SUMMARY_COLUMN_ID = "SummaryColumnId";
	public static String PROP_DISP_COLUMN_ID = "DispColumnId";
	public static String PROP_IS_TREE = "IsTree";
	public static String PROP_COMMENTS = "Comments";
	public static String PROP_PROPS = "Props";
	public static String PROP_IS_DROPDOWN = "IsDropdown";
	public static String PROP_DIRECTORY = "Directory";
	public static String PROP_CLASS_NAME = "ClassName";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";
	public static String PROP_PARENT_TABLE_ID = "ParentTableId";
	public static String PROP_AD_OBJUICONF_ID = "AdObjuiconfId";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.String _name;
	private String _aliasName;
	private java.lang.Integer _pkColumnId;
	private java.lang.Integer _realtableId;
	private java.lang.String _filter;
	private java.lang.String _description;
	private java.lang.Integer _akColumnId;
	private java.lang.String _mask;
	private java.lang.Integer _adTableCategoryId;
	private java.lang.Integer _orderno;
	private java.lang.String _comments;
	private java.lang.String _props;
	private java.lang.String _url;
	private java.lang.String _className;
	private java.lang.Integer _directoryId;
	private java.lang.String _hasTrigAc;
	private java.lang.String _trigAc;
	private java.lang.String _hasTrigAm;
	private java.lang.String _trigAm;
	private java.lang.String _hasTrigBm;
	private java.lang.String _trigBm;
	private java.lang.String _hasTrigBd;
	private java.lang.String _trigBd;
	private java.lang.String _procSubmit;
	private java.lang.String _isDispatchable;
	private java.lang.Integer _dispColumnId;
	private java.lang.String _isTree;
	private java.lang.String _isMenuObj;
	private java.lang.String _isSMS;
	private java.lang.String _isDropdown;
	private java.lang.Integer _rowCnt;
	private java.lang.Integer _parentColumnId;
	private java.lang.Integer _summaryColumnId;
	private java.lang.Integer _dkColumnId;
	private java.lang.Integer _uClobId;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;
	private java.lang.String _isBig;
	private java.lang.Integer _parentTableId;
	private java.lang.Integer _adObjuiconfId;
	// many to one
	private nds.model.AdTable _realtable;
	private nds.model.AdTableCategory _adTableCategory;
	private nds.model.Directory _directory;

	// collections
	private java.util.Set _adColumnSet;
	private java.util.Set _adAliastableSet;
	private java.util.Set _adRefbytableSet;
	

	// constructors
	public BaseAdTable () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseAdTable (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseAdTable (
		java.lang.Integer _id,
		nds.model.AdTableCategory _adTableCategory,
		java.lang.String _name,
		java.lang.String _description,
		java.lang.String _mask,
		java.lang.Integer _adTableCategoryId,
		java.lang.String _hasTrigAc,
		java.lang.String _hasTrigAm,
		java.lang.String _hasTrigBm,
		java.lang.String _hasTrigBd,
		java.lang.String _isDispatchable,
		java.lang.String _isTree,
		java.lang.String _isMenuObj,
		java.lang.String _isSMS,
		java.lang.String _isDropdown,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setAdTableCategory(_adTableCategory);
		this.setName(_name);
		this.setDescription(_description);
		this.setMask(_mask);
		this.setAdTableCategoryId(_adTableCategoryId);
		this.setHasTrigAc(_hasTrigAc);
		this.setHasTrigAm(_hasTrigAm);
		this.setHasTrigBm(_hasTrigBm);
		this.setHasTrigBd(_hasTrigBd);
		this.setIsDispatchable(_isDispatchable);
		this.setIsTree(_isTree);
		this.setIsMenuObj(_isMenuObj);
		this.setIsSMS(_isSMS);
		this.setIsDropdown(_isDropdown);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="assigned"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: NAME
	 */
	public java.lang.String getName () {
		return _name;
	}
	public java.lang.String getAliasName () {
		return _aliasName;
	}
	public void setAliasName (java.lang.String _name) {
		this._aliasName = _name;
	}
	/**
	 * Set the value related to the column: NAME
	 * @param _name the NAME value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: PK_COLUMN_ID
	 */
	public java.lang.Integer getPkColumnId () {
		return _pkColumnId;
	}

	/**
	 * Set the value related to the column: PK_COLUMN_ID
	 * @param _pkColumnId the PK_COLUMN_ID value
	 */
	public void setPkColumnId (java.lang.Integer _pkColumnId) {
		this._pkColumnId = _pkColumnId;
	}


	/**
	 * Return the value associated with the column: REALTABLE_ID
	 */
	public java.lang.Integer getRealtableId () {
		return _realtableId;
	}

	/**
	 * Set the value related to the column: REALTABLE_ID
	 * @param _realtableId the REALTABLE_ID value
	 */
	public void setRealtableId (java.lang.Integer _realtableId) {
		this._realtableId = _realtableId;
	}


	/**
	 * Return the value associated with the column: FILTER
	 */
	public java.lang.String getFilter () {
		return _filter;
	}

	/**
	 * Set the value related to the column: FILTER
	 * @param _filter the FILTER value
	 */
	public void setFilter (java.lang.String _filter) {
		this._filter = _filter;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: AK_COLUMN_ID
	 */
	public java.lang.Integer getAkColumnId () {
		return _akColumnId;
	}

	/**
	 * Set the value related to the column: AK_COLUMN_ID
	 * @param _akColumnId the AK_COLUMN_ID value
	 */
	public void setAkColumnId (java.lang.Integer _akColumnId) {
		this._akColumnId = _akColumnId;
	}


	/**
	 * Return the value associated with the column: MASK
	 */
	public java.lang.String getMask () {
		return _mask;
	}

	/**
	 * Set the value related to the column: MASK
	 * @param _mask the MASK value
	 */
	public void setMask (java.lang.String _mask) {
		this._mask = _mask;
	}


	/**
	 * Return the value associated with the column: AD_TABLECATEGORY_ID
	 */
	public java.lang.Integer getAdTableCategoryId () {
		return _adTableCategoryId;
	}

	/**
	 * Set the value related to the column: AD_TABLECATEGORY_ID
	 * @param _adTableCategoryId the AD_TABLECATEGORY_ID value
	 */
	public void setAdTableCategoryId (java.lang.Integer _adTableCategoryId) {
		this._adTableCategoryId = _adTableCategoryId;
	}


	/**
	 * Return the value associated with the column: ORDERNO
	 */
	public java.lang.Integer getOrderno () {
		return _orderno;
	}

	/**
	 * Set the value related to the column: ORDERNO
	 * @param _orderno the ORDERNO value
	 */
	public void setOrderno (java.lang.Integer _orderno) {
		this._orderno = _orderno;
	}


	/**
	 * Return the value associated with the column: COMMENTS
	 */
	public java.lang.String getComments () {
		return _comments;
	}

	/**
	 * Set the value related to the column: COMMENTS
	 * @param _comments the COMMENTS value
	 */
	public void setComments (java.lang.String _comments) {
		this._comments = _comments;
	}
	/**
	 * Return the value associated with the column: Props
	 */
	public java.lang.String getProps () {
		return _props;
	}

	/**
	 * Set the value related to the column: Props
	 * @param _comments the COMMENTS value
	 */
	public void setProps (java.lang.String _props) {
		this._props = _props;
	}

	/**
	 * Return the value associated with the column: URL
	 */
	public java.lang.String getUrl () {
		return _url;
	}

	/**
	 * Set the value related to the column: URL
	 * @param _url the URL value
	 */
	public void setUrl (java.lang.String _url) {
		this._url = _url;
	}


	/**
	 * Return the value associated with the column: CLASSNAME
	 */
	public java.lang.String getClassName () {
		return _className;
	}

	/**
	 * Set the value related to the column: CLASSNAME
	 * @param _className the CLASSNAME value
	 */
	public void setClassName (java.lang.String _className) {
		this._className = _className;
	}


	/**
	 * Return the value associated with the column: DIRECTORY_ID
	 */
	public java.lang.Integer getDirectoryId () {
		return _directoryId;
	}

	/**
	 * Set the value related to the column: DIRECTORY_ID
	 * @param _directoryId the DIRECTORY_ID value
	 */
	public void setDirectoryId (java.lang.Integer _directoryId) {
		this._directoryId = _directoryId;
	}


	/**
	 * Return the value associated with the column: HAS_TRIG_AC
	 */
	public java.lang.String getHasTrigAc () {
		return _hasTrigAc;
	}

	/**
	 * Set the value related to the column: HAS_TRIG_AC
	 * @param _hasTrigAc the HAS_TRIG_AC value
	 */
	public void setHasTrigAc (java.lang.String _hasTrigAc) {
		this._hasTrigAc = _hasTrigAc;
	}


	/**
	 * Return the value associated with the column: TRIG_AC
	 */
	public java.lang.String getTrigAc () {
		return _trigAc;
	}

	/**
	 * Set the value related to the column: TRIG_AC
	 * @param _trigAc the TRIG_AC value
	 */
	public void setTrigAc (java.lang.String _trigAc) {
		this._trigAc = _trigAc;
	}


	/**
	 * Return the value associated with the column: HAS_TRIG_AM
	 */
	public java.lang.String getHasTrigAm () {
		return _hasTrigAm;
	}

	/**
	 * Set the value related to the column: HAS_TRIG_AM
	 * @param _hasTrigAm the HAS_TRIG_AM value
	 */
	public void setHasTrigAm (java.lang.String _hasTrigAm) {
		this._hasTrigAm = _hasTrigAm;
	}


	/**
	 * Return the value associated with the column: TRIG_AM
	 */
	public java.lang.String getTrigAm () {
		return _trigAm;
	}

	/**
	 * Set the value related to the column: TRIG_AM
	 * @param _trigAm the TRIG_AM value
	 */
	public void setTrigAm (java.lang.String _trigAm) {
		this._trigAm = _trigAm;
	}


	/**
	 * Return the value associated with the column: HAS_TRIG_BM
	 */
	public java.lang.String getHasTrigBm () {
		return _hasTrigBm;
	}

	/**
	 * Set the value related to the column: HAS_TRIG_BM
	 * @param _hasTrigBm the HAS_TRIG_BM value
	 */
	public void setHasTrigBm (java.lang.String _hasTrigBm) {
		this._hasTrigBm = _hasTrigBm;
	}


	/**
	 * Return the value associated with the column: TRIG_BM
	 */
	public java.lang.String getTrigBm () {
		return _trigBm;
	}

	/**
	 * Set the value related to the column: TRIG_BM
	 * @param _trigBm the TRIG_BM value
	 */
	public void setTrigBm (java.lang.String _trigBm) {
		this._trigBm = _trigBm;
	}


	/**
	 * Return the value associated with the column: HAS_TRIG_BD
	 */
	public java.lang.String getHasTrigBd () {
		return _hasTrigBd;
	}

	/**
	 * Set the value related to the column: HAS_TRIG_BD
	 * @param _hasTrigBd the HAS_TRIG_BD value
	 */
	public void setHasTrigBd (java.lang.String _hasTrigBd) {
		this._hasTrigBd = _hasTrigBd;
	}


	/**
	 * Return the value associated with the column: TRIG_BD
	 */
	public java.lang.String getTrigBd () {
		return _trigBd;
	}

	/**
	 * Set the value related to the column: TRIG_BD
	 * @param _trigBd the TRIG_BD value
	 */
	public void setTrigBd (java.lang.String _trigBd) {
		this._trigBd = _trigBd;
	}


	/**
	 * Return the value associated with the column: PROC_SUBMIT
	 */
	public java.lang.String getProcSubmit () {
		return _procSubmit;
	}

	/**
	 * Set the value related to the column: PROC_SUBMIT
	 * @param _procSubmit the PROC_SUBMIT value
	 */
	public void setProcSubmit (java.lang.String _procSubmit) {
		this._procSubmit = _procSubmit;
	}


	/**
	 * Return the value associated with the column: ISDISPATCHABLE
	 */
	public java.lang.String getIsDispatchable () {
		return _isDispatchable;
	}

	/**
	 * Set the value related to the column: ISDISPATCHABLE
	 * @param _isDispatchable the ISDISPATCHABLE value
	 */
	public void setIsDispatchable (java.lang.String _isDispatchable) {
		this._isDispatchable = _isDispatchable;
	}


	/**
	 * Return the value associated with the column: DISP_COLUMN_ID
	 */
	public java.lang.Integer getDispColumnId () {
		return _dispColumnId;
	}

	/**
	 * Set the value related to the column: DISP_COLUMN_ID
	 * @param _dispColumnId the DISP_COLUMN_ID value
	 */
	public void setDispColumnId (java.lang.Integer _dispColumnId) {
		this._dispColumnId = _dispColumnId;
	}


	/**
	 * Return the value associated with the column: ISTREE
	 */
	public java.lang.String getIsTree () {
		return _isTree;
	}

	/**
	 * Set the value related to the column: ISTREE
	 * @param _isTree the ISTREE value
	 */
	public void setIsTree (java.lang.String _isTree) {
		this._isTree = _isTree;
	}


	/**
	 * Return the value associated with the column: ISMENUOBJ
	 */
	public java.lang.String getIsMenuObj () {
		return _isMenuObj;
	}

	/**
	 * Set the value related to the column: ISMENUOBJ
	 * @param _isMenuObj the ISMENUOBJ value
	 */
	public void setIsMenuObj (java.lang.String _isMenuObj) {
		this._isMenuObj = _isMenuObj;
	}


	/**
	 * Return the value associated with the column: ISSMS
	 */
	public java.lang.String getIsSMS () {
		return _isSMS;
	}

	/**
	 * Set the value related to the column: ISSMS
	 * @param _isSMS the ISSMS value
	 */
	public void setIsSMS (java.lang.String _isSMS) {
		this._isSMS = _isSMS;
	}


	/**
	 * Return the value associated with the column: ISDROPDOWN
	 */
	public java.lang.String getIsDropdown () {
		return _isDropdown;
	}

	/**
	 * Set the value related to the column: ISDROPDOWN
	 * @param _isDropdown the ISDROPDOWN value
	 */
	public void setIsDropdown (java.lang.String _isDropdown) {
		this._isDropdown = _isDropdown;
	}


	/**
	 * Return the value associated with the column: ROWCNT
	 */
	public java.lang.Integer getRowCnt () {
		return _rowCnt;
	}

	/**
	 * Set the value related to the column: ROWCNT
	 * @param _rowCnt the ROWCNT value
	 */
	public void setRowCnt (java.lang.Integer _rowCnt) {
		this._rowCnt = _rowCnt;
	}
	/**
	 * Return the value associated with the column: AD_OBJUICONF_ID
	 */
	public java.lang.Integer getAdObjuiconfId () {
		return this._adObjuiconfId;
	}

	/**
	 * Set the value related to the column: AD_OBJUICONF_ID
	 * @param oid the AD_OBJUICONF_ID value
	 */
	public void setAdObjuiconfId (java.lang.Integer oid) {
		this._adObjuiconfId = oid;
	}	
	/**
	 * Return the value associated with the column: PARENT_COLUMN_ID
	 */
	public java.lang.Integer getParentTableId () {
		return _parentTableId;
	}

	/**
	 * Set the value related to the column: PARENT_TABLE_ID
	 * @param _parentTableId the PARENT_TABLE_ID value
	 */
	public void setParentTableId (java.lang.Integer _parentTableId) {
		this._parentTableId = _parentTableId;
	}

	/**
	 * Return the value associated with the column: PARENT_COLUMN_ID
	 */
	public java.lang.Integer getParentColumnId () {
		return _parentColumnId;
	}

	/**
	 * Set the value related to the column: PARENT_COLUMN_ID
	 * @param _parentColumnId the PARENT_COLUMN_ID value
	 */
	public void setParentColumnId (java.lang.Integer _parentColumnId) {
		this._parentColumnId = _parentColumnId;
	}


	/**
	 * Return the value associated with the column: SUMMARY_COLUMN_ID
	 */
	public java.lang.Integer getSummaryColumnId () {
		return _summaryColumnId;
	}

	/**
	 * Set the value related to the column: SUMMARY_COLUMN_ID
	 * @param _summaryColumnId the SUMMARY_COLUMN_ID value
	 */
	public void setSummaryColumnId (java.lang.Integer _summaryColumnId) {
		this._summaryColumnId = _summaryColumnId;
	}


	/**
	 * Return the value associated with the column: DK_COLUMN_ID
	 */
	public java.lang.Integer getDkColumnId () {
		return _dkColumnId;
	}

	/**
	 * Set the value related to the column: DK_COLUMN_ID
	 * @param _dkColumnId the DK_COLUMN_ID value
	 */
	public void setDkColumnId (java.lang.Integer _dkColumnId) {
		this._dkColumnId = _dkColumnId;
	}


	/**
	 * Return the value associated with the column: U_CLOB_ID
	 */
	public java.lang.Integer getUClobId () {
		return _uClobId;
	}

	/**
	 * Set the value related to the column: U_CLOB_ID
	 * @param _uClobId the U_CLOB_ID value
	 */
	public void setUClobId (java.lang.Integer _uClobId) {
		this._uClobId = _uClobId;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
	 * Return the value associated with the column: ISBIG
	 */
	public java.lang.String getIsBig () {
		return _isBig;
	}

	/**
	 * Set the value related to the column: ISBIG
	 * @param _isBig the ISBIG value
	 */
	public void setIsBig (java.lang.String _isBig) {
		this._isBig = _isBig;
	}


	/**
     * @hibernate.property
     *  column=REALTABLE_ID
	 */
	public nds.model.AdTable getRealtable () {
		return this._realtable;
	}

	/**
	 * Set the value related to the column: REALTABLE_ID
	 * @param _realtable the REALTABLE_ID value
	 */
	public void setRealtable (nds.model.AdTable _realtable) {
		this._realtable = _realtable;
	}


	/**
     * @hibernate.property
     *  column=AD_TABLECATEGORY_ID
	 * not-null=true
	 */
	public nds.model.AdTableCategory getAdTableCategory () {
		return this._adTableCategory;
	}

	/**
	 * Set the value related to the column: AD_TABLECATEGORY_ID
	 * @param _adTableCategory the AD_TABLECATEGORY_ID value
	 */
	public void setAdTableCategory (nds.model.AdTableCategory _adTableCategory) {
		this._adTableCategory = _adTableCategory;
	}


	/**
     * @hibernate.property
     *  column=DIRECTORY_ID
	 */
	public nds.model.Directory getDirectory () {
		return this._directory;
	}

	/**
	 * Set the value related to the column: DIRECTORY_ID
	 * @param _directory the DIRECTORY_ID value
	 */
	public void setDirectory (nds.model.Directory _directory) {
		this._directory = _directory;
	}


	/**
	 * Return the value associated with the column: AdColumnSet
	 */
	public java.util.Set getAdColumnSet () {
		return this._adColumnSet;
	}

	/**
	 * Set the value related to the column: AdColumnSet
	 * @param _adColumnSet the AdColumnSet value
	 */
	public void setAdColumnSet (java.util.Set _adColumnSet) {
		this._adColumnSet = _adColumnSet;
	}
	
	public void addToAdColumnSet (Object obj) {
		if (null == this._adColumnSet) this._adColumnSet = new java.util.HashSet();
		this._adColumnSet.add(obj);
	}



	/**
	 * Return the value associated with the column: AdAliastableSet
	 */
	public java.util.Set getAdAliastableSet () {
		return this._adAliastableSet;
	}

	/**
	 * Set the value related to the column: AdAliastableSet
	 * @param _adAliastableSet the AdAliastableSet value
	 */
	public void setAdAliastableSet (java.util.Set _adAliastableSet) {
		this._adAliastableSet = _adAliastableSet;
	}
	
	public void addToAdAliastableSet (Object obj) {
		if (null == this._adAliastableSet) this._adAliastableSet = new java.util.HashSet();
		this._adAliastableSet.add(obj);
	}



	/**
	 * Return the value associated with the column: AdRefbytableSet
	 */
	public java.util.Set getAdRefbytableSet () {
		return this._adRefbytableSet;
	}

	/**
	 * Set the value related to the column: AdRefbytableSet
	 * @param _adRefbytableSet the AdRefbytableSet value
	 */
	public void setAdRefbytableSet (java.util.Set _adRefbytableSet) {
		this._adRefbytableSet = _adRefbytableSet;
	}
	
	public void addToAdRefbytableSet (Object obj) {
		if (null == this._adRefbytableSet) this._adRefbytableSet = new java.util.HashSet();
		this._adRefbytableSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseAdTable)) return false;
		else {
			nds.model.base.BaseAdTable mObj = (nds.model.base.BaseAdTable) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}