package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the M_PRODUCT table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="M_PRODUCT"
 */
public abstract class BaseMProduct  implements Serializable {

	public static String PROP_C_TAX_CATEGORY_ID = "CTaxCategoryId";
	public static String PROP_C_TAX_CATEGORY = "CTaxCategory";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_M_PRODUCT_CATEGORY_ID = "MProductCategoryId";
	public static String PROP_M_LOCATOR_ID = "MLocatorId";
	public static String PROP_C_UOM = "CUom";
	public static String PROP_SHELFWIDTH = "Shelfwidth";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_IS_STOCKED = "IsStocked";
	public static String PROP_DOCUMENTNOTE = "Documentnote";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_VERSIONNO = "Versionno";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_IS_SUMMARY = "IsSummary";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_IMAGEURL = "Imageurl";
	public static String PROP_M_ATTRIBUTE_SET_INSTANCE_ID = "MAttributeSetInstanceId";
	public static String PROP_C_UOM_ID = "CUomId";
	public static String PROP_NAME = "Name";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_UPC = "Upc";
	public static String PROP_SALESREP_ID = "SalesrepId";
	public static String PROP_SKU = "Sku";
	public static String PROP_SHELFDEPTH = "Shelfdepth";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_SALESREP = "Salesrep";
	public static String PROP_DESCRIPTIONURL = "Descriptionurl";
	public static String PROP_M_ATTRIBUTE_SET_INSTANCE = "MAttributeSetInstance";
	public static String PROP_WEIGHT = "Weight";
	public static String PROP_GUARANTEEDAYS = "Guaranteedays";
	public static String PROP_M_ATTRIBUTE_SET_ID = "MAttributeSetId";
	public static String PROP_M_PRODUCT_CATEGORY = "MProductCategory";
	public static String PROP_M_ATTRIBUTE_SET = "MAttributeSet";
	public static String PROP_SHELFHEIGHT = "Shelfheight";
	public static String PROP_IS_SOLD = "IsSold";
	public static String PROP_VOLUME = "Volume";
	public static String PROP_M_LOCATOR = "MLocator";
	public static String PROP_IS_PURCHASED = "IsPurchased";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _name;
	private java.lang.String _description;
	private java.lang.String _upc;
	private java.lang.String _sku;
	private java.lang.Integer _cUomId;
	private java.lang.Integer _salesrepId;
	private java.lang.String _isSummary;
	private java.lang.String _isStocked;
	private java.lang.String _isPurchased;
	private java.lang.String _isSold;
	private java.lang.Integer _mProductCategoryId;
	private double _volume;
	private double _weight;
	private double _shelfwidth;
	private double _shelfheight;
	private double _shelfdepth;
	private java.lang.Integer _cTaxCategoryId;
	private java.lang.String _imageurl;
	private java.lang.String _descriptionurl;
	private java.lang.Integer _guaranteedays;
	private java.lang.String _versionno;
	private java.lang.Integer _mAttributeSetId;
	private java.lang.Integer _mAttributeSetInstanceId;
	private java.lang.Integer _mLocatorId;
	private java.lang.String _documentnote;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.CUom _cUom;
	private nds.model.Users _salesrep;
	private nds.model.MProductCategory _mProductCategory;
	private nds.model.CTaxCategory _cTaxCategory;
	private nds.model.MAttributeSet _mAttributeSet;
	private nds.model.MAttributeSetInstance _mAttributeSetInstance;
	private nds.model.MLocator _mLocator;


	// constructors
	public BaseMProduct () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMProduct (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseMProduct (
		java.lang.Integer _id,
		java.lang.String _name,
		java.lang.String _isSummary,
		java.lang.String _isStocked,
		java.lang.String _isPurchased,
		java.lang.String _isSold,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setName(_name);
		this.setIsSummary(_isSummary);
		this.setIsStocked(_isStocked);
		this.setIsPurchased(_isPurchased);
		this.setIsSold(_isSold);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: NAME
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: NAME
	 * @param _name the NAME value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: UPC
	 */
	public java.lang.String getUpc () {
		return _upc;
	}

	/**
	 * Set the value related to the column: UPC
	 * @param _upc the UPC value
	 */
	public void setUpc (java.lang.String _upc) {
		this._upc = _upc;
	}


	/**
	 * Return the value associated with the column: SKU
	 */
	public java.lang.String getSku () {
		return _sku;
	}

	/**
	 * Set the value related to the column: SKU
	 * @param _sku the SKU value
	 */
	public void setSku (java.lang.String _sku) {
		this._sku = _sku;
	}


	/**
	 * Return the value associated with the column: C_UOM_ID
	 */
	public java.lang.Integer getCUomId () {
		return _cUomId;
	}

	/**
	 * Set the value related to the column: C_UOM_ID
	 * @param _cUomId the C_UOM_ID value
	 */
	public void setCUomId (java.lang.Integer _cUomId) {
		this._cUomId = _cUomId;
	}


	/**
	 * Return the value associated with the column: SALESREP_ID
	 */
	public java.lang.Integer getSalesrepId () {
		return _salesrepId;
	}

	/**
	 * Set the value related to the column: SALESREP_ID
	 * @param _salesrepId the SALESREP_ID value
	 */
	public void setSalesrepId (java.lang.Integer _salesrepId) {
		this._salesrepId = _salesrepId;
	}


	/**
	 * Return the value associated with the column: ISSUMMARY
	 */
	public java.lang.String getIsSummary () {
		return _isSummary;
	}

	/**
	 * Set the value related to the column: ISSUMMARY
	 * @param _isSummary the ISSUMMARY value
	 */
	public void setIsSummary (java.lang.String _isSummary) {
		this._isSummary = _isSummary;
	}


	/**
	 * Return the value associated with the column: ISSTOCKED
	 */
	public java.lang.String getIsStocked () {
		return _isStocked;
	}

	/**
	 * Set the value related to the column: ISSTOCKED
	 * @param _isStocked the ISSTOCKED value
	 */
	public void setIsStocked (java.lang.String _isStocked) {
		this._isStocked = _isStocked;
	}


	/**
	 * Return the value associated with the column: ISPURCHASED
	 */
	public java.lang.String getIsPurchased () {
		return _isPurchased;
	}

	/**
	 * Set the value related to the column: ISPURCHASED
	 * @param _isPurchased the ISPURCHASED value
	 */
	public void setIsPurchased (java.lang.String _isPurchased) {
		this._isPurchased = _isPurchased;
	}


	/**
	 * Return the value associated with the column: ISSOLD
	 */
	public java.lang.String getIsSold () {
		return _isSold;
	}

	/**
	 * Set the value related to the column: ISSOLD
	 * @param _isSold the ISSOLD value
	 */
	public void setIsSold (java.lang.String _isSold) {
		this._isSold = _isSold;
	}


	/**
	 * Return the value associated with the column: M_PRODUCT_CATEGORY_ID
	 */
	public java.lang.Integer getMProductCategoryId () {
		return _mProductCategoryId;
	}

	/**
	 * Set the value related to the column: M_PRODUCT_CATEGORY_ID
	 * @param _mProductCategoryId the M_PRODUCT_CATEGORY_ID value
	 */
	public void setMProductCategoryId (java.lang.Integer _mProductCategoryId) {
		this._mProductCategoryId = _mProductCategoryId;
	}


	/**
	 * Return the value associated with the column: VOLUME
	 */
	public double getVolume () {
		return _volume;
	}

	/**
	 * Set the value related to the column: VOLUME
	 * @param _volume the VOLUME value
	 */
	public void setVolume (double _volume) {
		this._volume = _volume;
	}


	/**
	 * Return the value associated with the column: WEIGHT
	 */
	public double getWeight () {
		return _weight;
	}

	/**
	 * Set the value related to the column: WEIGHT
	 * @param _weight the WEIGHT value
	 */
	public void setWeight (double _weight) {
		this._weight = _weight;
	}


	/**
	 * Return the value associated with the column: SHELFWIDTH
	 */
	public double getShelfwidth () {
		return _shelfwidth;
	}

	/**
	 * Set the value related to the column: SHELFWIDTH
	 * @param _shelfwidth the SHELFWIDTH value
	 */
	public void setShelfwidth (double _shelfwidth) {
		this._shelfwidth = _shelfwidth;
	}


	/**
	 * Return the value associated with the column: SHELFHEIGHT
	 */
	public double getShelfheight () {
		return _shelfheight;
	}

	/**
	 * Set the value related to the column: SHELFHEIGHT
	 * @param _shelfheight the SHELFHEIGHT value
	 */
	public void setShelfheight (double _shelfheight) {
		this._shelfheight = _shelfheight;
	}


	/**
	 * Return the value associated with the column: SHELFDEPTH
	 */
	public double getShelfdepth () {
		return _shelfdepth;
	}

	/**
	 * Set the value related to the column: SHELFDEPTH
	 * @param _shelfdepth the SHELFDEPTH value
	 */
	public void setShelfdepth (double _shelfdepth) {
		this._shelfdepth = _shelfdepth;
	}


	/**
	 * Return the value associated with the column: C_TAXCATEGORY_ID
	 */
	public java.lang.Integer getCTaxCategoryId () {
		return _cTaxCategoryId;
	}

	/**
	 * Set the value related to the column: C_TAXCATEGORY_ID
	 * @param _cTaxCategoryId the C_TAXCATEGORY_ID value
	 */
	public void setCTaxCategoryId (java.lang.Integer _cTaxCategoryId) {
		this._cTaxCategoryId = _cTaxCategoryId;
	}


	/**
	 * Return the value associated with the column: IMAGEURL
	 */
	public java.lang.String getImageurl () {
		return _imageurl;
	}

	/**
	 * Set the value related to the column: IMAGEURL
	 * @param _imageurl the IMAGEURL value
	 */
	public void setImageurl (java.lang.String _imageurl) {
		this._imageurl = _imageurl;
	}


	/**
	 * Return the value associated with the column: DESCRIPTIONURL
	 */
	public java.lang.String getDescriptionurl () {
		return _descriptionurl;
	}

	/**
	 * Set the value related to the column: DESCRIPTIONURL
	 * @param _descriptionurl the DESCRIPTIONURL value
	 */
	public void setDescriptionurl (java.lang.String _descriptionurl) {
		this._descriptionurl = _descriptionurl;
	}


	/**
	 * Return the value associated with the column: GUARANTEEDAYS
	 */
	public java.lang.Integer getGuaranteedays () {
		return _guaranteedays;
	}

	/**
	 * Set the value related to the column: GUARANTEEDAYS
	 * @param _guaranteedays the GUARANTEEDAYS value
	 */
	public void setGuaranteedays (java.lang.Integer _guaranteedays) {
		this._guaranteedays = _guaranteedays;
	}


	/**
	 * Return the value associated with the column: VERSIONNO
	 */
	public java.lang.String getVersionno () {
		return _versionno;
	}

	/**
	 * Set the value related to the column: VERSIONNO
	 * @param _versionno the VERSIONNO value
	 */
	public void setVersionno (java.lang.String _versionno) {
		this._versionno = _versionno;
	}


	/**
	 * Return the value associated with the column: M_ATTRIBUTESET_ID
	 */
	public java.lang.Integer getMAttributeSetId () {
		return _mAttributeSetId;
	}

	/**
	 * Set the value related to the column: M_ATTRIBUTESET_ID
	 * @param _mAttributeSetId the M_ATTRIBUTESET_ID value
	 */
	public void setMAttributeSetId (java.lang.Integer _mAttributeSetId) {
		this._mAttributeSetId = _mAttributeSetId;
	}


	/**
	 * Return the value associated with the column: M_ATTRIBUTESETINSTANCE_ID
	 */
	public java.lang.Integer getMAttributeSetInstanceId () {
		return _mAttributeSetInstanceId;
	}

	/**
	 * Set the value related to the column: M_ATTRIBUTESETINSTANCE_ID
	 * @param _mAttributeSetInstanceId the M_ATTRIBUTESETINSTANCE_ID value
	 */
	public void setMAttributeSetInstanceId (java.lang.Integer _mAttributeSetInstanceId) {
		this._mAttributeSetInstanceId = _mAttributeSetInstanceId;
	}


	/**
	 * Return the value associated with the column: M_LOCATOR_ID
	 */
	public java.lang.Integer getMLocatorId () {
		return _mLocatorId;
	}

	/**
	 * Set the value related to the column: M_LOCATOR_ID
	 * @param _mLocatorId the M_LOCATOR_ID value
	 */
	public void setMLocatorId (java.lang.Integer _mLocatorId) {
		this._mLocatorId = _mLocatorId;
	}


	/**
	 * Return the value associated with the column: DOCUMENTNOTE
	 */
	public java.lang.String getDocumentnote () {
		return _documentnote;
	}

	/**
	 * Set the value related to the column: DOCUMENTNOTE
	 * @param _documentnote the DOCUMENTNOTE value
	 */
	public void setDocumentnote (java.lang.String _documentnote) {
		this._documentnote = _documentnote;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=C_UOM_ID
	 */
	public nds.model.CUom getCUom () {
		return this._cUom;
	}

	/**
	 * Set the value related to the column: C_UOM_ID
	 * @param _cUom the C_UOM_ID value
	 */
	public void setCUom (nds.model.CUom _cUom) {
		this._cUom = _cUom;
	}


	/**
     * @hibernate.property
     *  column=SALESREP_ID
	 */
	public nds.model.Users getSalesrep () {
		return this._salesrep;
	}

	/**
	 * Set the value related to the column: SALESREP_ID
	 * @param _salesrep the SALESREP_ID value
	 */
	public void setSalesrep (nds.model.Users _salesrep) {
		this._salesrep = _salesrep;
	}


	/**
     * @hibernate.property
     *  column=M_PRODUCT_CATEGORY_ID
	 */
	public nds.model.MProductCategory getMProductCategory () {
		return this._mProductCategory;
	}

	/**
	 * Set the value related to the column: M_PRODUCT_CATEGORY_ID
	 * @param _mProductCategory the M_PRODUCT_CATEGORY_ID value
	 */
	public void setMProductCategory (nds.model.MProductCategory _mProductCategory) {
		this._mProductCategory = _mProductCategory;
	}


	/**
     * @hibernate.property
     *  column=C_TAXCATEGORY_ID
	 */
	public nds.model.CTaxCategory getCTaxCategory () {
		return this._cTaxCategory;
	}

	/**
	 * Set the value related to the column: C_TAXCATEGORY_ID
	 * @param _cTaxCategory the C_TAXCATEGORY_ID value
	 */
	public void setCTaxCategory (nds.model.CTaxCategory _cTaxCategory) {
		this._cTaxCategory = _cTaxCategory;
	}


	/**
     * @hibernate.property
     *  column=M_ATTRIBUTESET_ID
	 */
	public nds.model.MAttributeSet getMAttributeSet () {
		return this._mAttributeSet;
	}

	/**
	 * Set the value related to the column: M_ATTRIBUTESET_ID
	 * @param _mAttributeSet the M_ATTRIBUTESET_ID value
	 */
	public void setMAttributeSet (nds.model.MAttributeSet _mAttributeSet) {
		this._mAttributeSet = _mAttributeSet;
	}


	/**
     * @hibernate.property
     *  column=M_ATTRIBUTESETINSTANCE_ID
	 */
	public nds.model.MAttributeSetInstance getMAttributeSetInstance () {
		return this._mAttributeSetInstance;
	}

	/**
	 * Set the value related to the column: M_ATTRIBUTESETINSTANCE_ID
	 * @param _mAttributeSetInstance the M_ATTRIBUTESETINSTANCE_ID value
	 */
	public void setMAttributeSetInstance (nds.model.MAttributeSetInstance _mAttributeSetInstance) {
		this._mAttributeSetInstance = _mAttributeSetInstance;
	}


	/**
     * @hibernate.property
     *  column=M_LOCATOR_ID
	 */
	public nds.model.MLocator getMLocator () {
		return this._mLocator;
	}

	/**
	 * Set the value related to the column: M_LOCATOR_ID
	 * @param _mLocator the M_LOCATOR_ID value
	 */
	public void setMLocator (nds.model.MLocator _mLocator) {
		this._mLocator = _mLocator;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseMProduct)) return false;
		else {
			nds.model.base.BaseMProduct mObj = (nds.model.base.BaseMProduct) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}