package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the C_LOCATION table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="C_LOCATION"
 */
public abstract class BaseCLocation  implements Serializable {

	public static String PROP_C_CITY = "CCity";
	public static String PROP_C_COUNTRY = "CCountry";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_ADDRESS1 = "Address1";
	public static String PROP_POSTAL = "Postal";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_CITY = "City";
	public static String PROP_C_REGION = "CRegion";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_C_COUNTRY_ID = "CCountryId";
	public static String PROP_ADDRESS4 = "Address4";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_REGION_NAME = "RegionName";
	public static String PROP_ADDRESS3 = "Address3";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_C_REGION_ID = "CRegionId";
	public static String PROP_C_CITY_ID = "CCityId";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_ID = "Id";
	public static String PROP_ADDRESS2 = "Address2";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _address1;
	private java.lang.String _address2;
	private java.lang.String _address3;
	private java.lang.String _address4;
	private java.lang.String _city;
	private java.lang.String _regionName;
	private java.lang.String _postal;
	private java.lang.Integer _cCountryId;
	private java.lang.Integer _cRegionId;
	private java.lang.Integer _cCityId;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.CCountry _cCountry;
	private nds.model.CRegion _cRegion;
	private nds.model.CCity _cCity;


	// constructors
	public BaseCLocation () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCLocation (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCLocation (
		java.lang.Integer _id,
		java.lang.String _address1,
		java.lang.String _address2,
		java.lang.String _address3,
		java.lang.String _address4,
		java.lang.String _city,
		java.lang.String _regionName,
		java.lang.String _postal,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setAddress1(_address1);
		this.setAddress2(_address2);
		this.setAddress3(_address3);
		this.setAddress4(_address4);
		this.setCity(_city);
		this.setRegionName(_regionName);
		this.setPostal(_postal);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: ADDRESS1
	 */
	public java.lang.String getAddress1 () {
		return _address1;
	}

	/**
	 * Set the value related to the column: ADDRESS1
	 * @param _address1 the ADDRESS1 value
	 */
	public void setAddress1 (java.lang.String _address1) {
		this._address1 = _address1;
	}


	/**
	 * Return the value associated with the column: ADDRESS2
	 */
	public java.lang.String getAddress2 () {
		return _address2;
	}

	/**
	 * Set the value related to the column: ADDRESS2
	 * @param _address2 the ADDRESS2 value
	 */
	public void setAddress2 (java.lang.String _address2) {
		this._address2 = _address2;
	}


	/**
	 * Return the value associated with the column: ADDRESS3
	 */
	public java.lang.String getAddress3 () {
		return _address3;
	}

	/**
	 * Set the value related to the column: ADDRESS3
	 * @param _address3 the ADDRESS3 value
	 */
	public void setAddress3 (java.lang.String _address3) {
		this._address3 = _address3;
	}


	/**
	 * Return the value associated with the column: ADDRESS4
	 */
	public java.lang.String getAddress4 () {
		return _address4;
	}

	/**
	 * Set the value related to the column: ADDRESS4
	 * @param _address4 the ADDRESS4 value
	 */
	public void setAddress4 (java.lang.String _address4) {
		this._address4 = _address4;
	}


	/**
	 * Return the value associated with the column: CITY
	 */
	public java.lang.String getCity () {
		return _city;
	}

	/**
	 * Set the value related to the column: CITY
	 * @param _city the CITY value
	 */
	public void setCity (java.lang.String _city) {
		this._city = _city;
	}


	/**
	 * Return the value associated with the column: REGIONNAME
	 */
	public java.lang.String getRegionName () {
		return _regionName;
	}

	/**
	 * Set the value related to the column: REGIONNAME
	 * @param _regionName the REGIONNAME value
	 */
	public void setRegionName (java.lang.String _regionName) {
		this._regionName = _regionName;
	}


	/**
	 * Return the value associated with the column: POSTAL
	 */
	public java.lang.String getPostal () {
		return _postal;
	}

	/**
	 * Set the value related to the column: POSTAL
	 * @param _postal the POSTAL value
	 */
	public void setPostal (java.lang.String _postal) {
		this._postal = _postal;
	}


	/**
	 * Return the value associated with the column: C_COUNTRY_ID
	 */
	public java.lang.Integer getCCountryId () {
		return _cCountryId;
	}

	/**
	 * Set the value related to the column: C_COUNTRY_ID
	 * @param _cCountryId the C_COUNTRY_ID value
	 */
	public void setCCountryId (java.lang.Integer _cCountryId) {
		this._cCountryId = _cCountryId;
	}


	/**
	 * Return the value associated with the column: C_REGION_ID
	 */
	public java.lang.Integer getCRegionId () {
		return _cRegionId;
	}

	/**
	 * Set the value related to the column: C_REGION_ID
	 * @param _cRegionId the C_REGION_ID value
	 */
	public void setCRegionId (java.lang.Integer _cRegionId) {
		this._cRegionId = _cRegionId;
	}


	/**
	 * Return the value associated with the column: C_CITY_ID
	 */
	public java.lang.Integer getCCityId () {
		return _cCityId;
	}

	/**
	 * Set the value related to the column: C_CITY_ID
	 * @param _cCityId the C_CITY_ID value
	 */
	public void setCCityId (java.lang.Integer _cCityId) {
		this._cCityId = _cCityId;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=C_COUNTRY_ID
	 */
	public nds.model.CCountry getCCountry () {
		return this._cCountry;
	}

	/**
	 * Set the value related to the column: C_COUNTRY_ID
	 * @param _cCountry the C_COUNTRY_ID value
	 */
	public void setCCountry (nds.model.CCountry _cCountry) {
		this._cCountry = _cCountry;
	}


	/**
     * @hibernate.property
     *  column=C_REGION_ID
	 */
	public nds.model.CRegion getCRegion () {
		return this._cRegion;
	}

	/**
	 * Set the value related to the column: C_REGION_ID
	 * @param _cRegion the C_REGION_ID value
	 */
	public void setCRegion (nds.model.CRegion _cRegion) {
		this._cRegion = _cRegion;
	}


	/**
     * @hibernate.property
     *  column=C_CITY_ID
	 */
	public nds.model.CCity getCCity () {
		return this._cCity;
	}

	/**
	 * Set the value related to the column: C_CITY_ID
	 * @param _cCity the C_CITY_ID value
	 */
	public void setCCity (nds.model.CCity _cCity) {
		this._cCity = _cCity;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseCLocation)) return false;
		else {
			nds.model.base.BaseCLocation mObj = (nds.model.base.BaseCLocation) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}