package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the C_BP_BANKACCOUNT table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="C_BP_BANKACCOUNT"
 */
public abstract class BaseCBpBankAccount  implements Serializable {

	public static String PROP_A_CITY = "ACity";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_A_ZIP = "AZip";
	public static String PROP_C_BANK = "CBank";
	public static String PROP_CREDITCARDNUMBER = "Creditcardnumber";
	public static String PROP_A_EMAIL = "AEmail";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_A_COUNTRY = "ACountry";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_A_NAME = "AName";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_C_BANK_ID = "CBankId";
	public static String PROP_A_STATE = "AState";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_C_BPARTNER = "CBpartner";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_A_STREET = "AStreet";
	public static String PROP_ACCOUNTNO = "Accountno";
	public static String PROP_C_BPARTNER_ID = "CBpartnerId";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _accountno;
	private java.lang.Integer _cBpartnerId;
	private java.lang.Integer _cBankId;
	private java.lang.String _creditcardnumber;
	private java.lang.String _aName;
	private java.lang.String _aStreet;
	private java.lang.String _aZip;
	private java.lang.String _aCity;
	private java.lang.String _aState;
	private java.lang.String _aCountry;
	private java.lang.String _aEmail;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.CBpartner _cBpartner;
	private nds.model.CBank _cBank;


	// constructors
	public BaseCBpBankAccount () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCBpBankAccount (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCBpBankAccount (
		java.lang.Integer _id,
		java.lang.String _accountno,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setAccountno(_accountno);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: ACCOUNTNO
	 */
	public java.lang.String getAccountno () {
		return _accountno;
	}

	/**
	 * Set the value related to the column: ACCOUNTNO
	 * @param _accountno the ACCOUNTNO value
	 */
	public void setAccountno (java.lang.String _accountno) {
		this._accountno = _accountno;
	}


	/**
	 * Return the value associated with the column: C_BPARTNER_ID
	 */
	public java.lang.Integer getCBpartnerId () {
		return _cBpartnerId;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartnerId the C_BPARTNER_ID value
	 */
	public void setCBpartnerId (java.lang.Integer _cBpartnerId) {
		this._cBpartnerId = _cBpartnerId;
	}


	/**
	 * Return the value associated with the column: C_BANK_ID
	 */
	public java.lang.Integer getCBankId () {
		return _cBankId;
	}

	/**
	 * Set the value related to the column: C_BANK_ID
	 * @param _cBankId the C_BANK_ID value
	 */
	public void setCBankId (java.lang.Integer _cBankId) {
		this._cBankId = _cBankId;
	}


	/**
	 * Return the value associated with the column: CREDITCARDNUMBER
	 */
	public java.lang.String getCreditcardnumber () {
		return _creditcardnumber;
	}

	/**
	 * Set the value related to the column: CREDITCARDNUMBER
	 * @param _creditcardnumber the CREDITCARDNUMBER value
	 */
	public void setCreditcardnumber (java.lang.String _creditcardnumber) {
		this._creditcardnumber = _creditcardnumber;
	}


	/**
	 * Return the value associated with the column: A_NAME
	 */
	public java.lang.String getAName () {
		return _aName;
	}

	/**
	 * Set the value related to the column: A_NAME
	 * @param _aName the A_NAME value
	 */
	public void setAName (java.lang.String _aName) {
		this._aName = _aName;
	}


	/**
	 * Return the value associated with the column: A_STREET
	 */
	public java.lang.String getAStreet () {
		return _aStreet;
	}

	/**
	 * Set the value related to the column: A_STREET
	 * @param _aStreet the A_STREET value
	 */
	public void setAStreet (java.lang.String _aStreet) {
		this._aStreet = _aStreet;
	}


	/**
	 * Return the value associated with the column: A_ZIP
	 */
	public java.lang.String getAZip () {
		return _aZip;
	}

	/**
	 * Set the value related to the column: A_ZIP
	 * @param _aZip the A_ZIP value
	 */
	public void setAZip (java.lang.String _aZip) {
		this._aZip = _aZip;
	}


	/**
	 * Return the value associated with the column: A_CITY
	 */
	public java.lang.String getACity () {
		return _aCity;
	}

	/**
	 * Set the value related to the column: A_CITY
	 * @param _aCity the A_CITY value
	 */
	public void setACity (java.lang.String _aCity) {
		this._aCity = _aCity;
	}


	/**
	 * Return the value associated with the column: A_STATE
	 */
	public java.lang.String getAState () {
		return _aState;
	}

	/**
	 * Set the value related to the column: A_STATE
	 * @param _aState the A_STATE value
	 */
	public void setAState (java.lang.String _aState) {
		this._aState = _aState;
	}


	/**
	 * Return the value associated with the column: A_COUNTRY
	 */
	public java.lang.String getACountry () {
		return _aCountry;
	}

	/**
	 * Set the value related to the column: A_COUNTRY
	 * @param _aCountry the A_COUNTRY value
	 */
	public void setACountry (java.lang.String _aCountry) {
		this._aCountry = _aCountry;
	}


	/**
	 * Return the value associated with the column: A_EMAIL
	 */
	public java.lang.String getAEmail () {
		return _aEmail;
	}

	/**
	 * Set the value related to the column: A_EMAIL
	 * @param _aEmail the A_EMAIL value
	 */
	public void setAEmail (java.lang.String _aEmail) {
		this._aEmail = _aEmail;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=C_BPARTNER_ID
	 */
	public nds.model.CBpartner getCBpartner () {
		return this._cBpartner;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartner the C_BPARTNER_ID value
	 */
	public void setCBpartner (nds.model.CBpartner _cBpartner) {
		this._cBpartner = _cBpartner;
	}


	/**
     * @hibernate.property
     *  column=C_BANK_ID
	 */
	public nds.model.CBank getCBank () {
		return this._cBank;
	}

	/**
	 * Set the value related to the column: C_BANK_ID
	 * @param _cBank the C_BANK_ID value
	 */
	public void setCBank (nds.model.CBank _cBank) {
		this._cBank = _cBank;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseCBpBankAccount)) return false;
		else {
			nds.model.base.BaseCBpBankAccount mObj = (nds.model.base.BaseCBpBankAccount) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}