package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the C_ORDER table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="C_ORDER"
 */
public abstract class BaseCOrder  implements Serializable {

	public static String PROP_AD_USER_ID = "AdUserId";
	public static String PROP_M_SHIPPER = "MShipper";
	public static String PROP_BILL_BPARTNER = "BillBpartner";
	public static String PROP_DELIVERY_RULE = "DeliveryRule";
	public static String PROP_TOT_SUM = "TotSum";
	public static String PROP_BILL_BPARTNER_ID = "BillBpartnerId";
	public static String PROP_PAYMENT_RULE = "PaymentRule";
	public static String PROP_FREIGHT_COST_RULE = "FreightCostRule";
	public static String PROP_PAY_BPARTNER_ID = "PayBpartnerId";
	public static String PROP_CHARGE_AMT = "ChargeAmt";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_BILL_LOCATION_ID = "BillLocationId";
	public static String PROP_C_BPARTNER_ID = "CBpartnerId";
	public static String PROP_BILL_USER = "BillUser";
	public static String PROP_DELIVERYVIA_RULE = "DeliveryviaRule";
	public static String PROP_SALESREP_ID = "SalesrepId";
	public static String PROP_C_BPARTNER_LOCATION_ID = "CBpartnerLocationId";
	public static String PROP_FREIGHT_AMT = "FreightAmt";
	public static String PROP_BILL_LOCATION = "BillLocation";
	public static String PROP_PAY_LOCATION = "PayLocation";
	public static String PROP_M_WAREHOUSE_ID = "MWarehouseId";
	public static String PROP_C_BPARTNER = "CBpartner";
	public static String PROP_M_SHIPPER_ID = "MShipperId";
	public static String PROP_C_BPARTNER_LOCATION = "CBpartnerLocation";
	public static String PROP_C_CHARGE = "CCharge";
	public static String PROP_REF_ORDER_ID = "RefOrderId";
	public static String PROP_STATUS = "Status";
	public static String PROP_PAY_LOCATION_ID = "PayLocationId";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_C_PAYMENT_ID = "CPaymentId";
	public static String PROP_PRIORITY_RULE = "PriorityRule";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_M_WAREHOUSE = "MWarehouse";
	public static String PROP_IS_TAXINCLUDED = "IsTaxincluded";
	public static String PROP_REF_CROSSORDER = "RefCrossorder";
	public static String PROP_REF_ORDER = "RefOrder";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_DOCNO = "Docno";
	public static String PROP_C_CHARGE_ID = "CChargeId";
	public static String PROP_BILL_USER_ID = "BillUserId";
	public static String PROP_DOC_TYPE = "DocType";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_TARGETDOC_TYPE = "TargetdocType";
	public static String PROP_SENDEMAIL = "Sendemail";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_C_PAYMENT = "CPayment";
	public static String PROP_SALESREP = "Salesrep";
	public static String PROP_INVOICE_RULE = "InvoiceRule";
	public static String PROP_TOT_QTY = "TotQty";
	public static String PROP_REF_CROSSORDER_ID = "RefCrossorderId";
	public static String PROP_PAY_BPARTNER = "PayBpartner";
	public static String PROP_AD_USER = "AdUser";
	public static String PROP_TOT_LINES = "TotLines";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _docno;
	private java.lang.String _docType;
	private java.lang.String _targetdocType;
	private java.lang.String _description;
	private java.lang.Integer _salesrepId;
	private java.lang.Integer _cBpartnerId;
	private java.lang.Integer _cBpartnerLocationId;
	private java.lang.String _paymentRule;
	private java.lang.String _invoiceRule;
	private java.lang.String _deliveryRule;
	private java.lang.String _freightCostRule;
	private double _freightAmt;
	private java.lang.String _deliveryviaRule;
	private java.lang.Integer _mShipperId;
	private java.lang.Integer _cChargeId;
	private double _chargeAmt;
	private java.lang.String _priorityRule;
	private java.lang.Integer _mWarehouseId;
	private java.lang.String _isTaxincluded;
	private java.lang.Integer _cPaymentId;
	private java.lang.String _sendemail;
	private java.lang.Integer _adUserId;
	private java.lang.Integer _billBpartnerId;
	private java.lang.Integer _billLocationId;
	private java.lang.Integer _billUserId;
	private java.lang.Integer _payBpartnerId;
	private java.lang.Integer _payLocationId;
	private java.lang.Integer _refOrderId;
	private java.lang.Integer _refCrossorderId;
	private java.lang.Integer _totLines;
	private java.lang.Integer _totQty;
	private double _totSum;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;
	private java.lang.Integer _status;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.Users _salesrep;
	private nds.model.CBpartner _cBpartner;
	private nds.model.CBpartnerLocation _cBpartnerLocation;
	private nds.model.MShipper _mShipper;
	private nds.model.CCharge _cCharge;
	private nds.model.MWarehouse _mWarehouse;
	private nds.model.CPayment _cPayment;
	private nds.model.Users _adUser;
	private nds.model.CBpartner _billBpartner;
	private nds.model.CBpartnerLocation _billLocation;
	private nds.model.Users _billUser;
	private nds.model.CBpartner _payBpartner;
	private nds.model.CBpartnerLocation _payLocation;
	private nds.model.COrder _refOrder;
	private nds.model.CCrossorder _refCrossorder;


	// constructors
	public BaseCOrder () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCOrder (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCOrder (
		java.lang.Integer _id,
		java.lang.String _docno,
		java.lang.String _docType,
		java.lang.String _targetdocType,
		java.lang.String _description,
		java.lang.String _paymentRule,
		java.lang.String _invoiceRule,
		java.lang.String _deliveryRule,
		java.lang.String _freightCostRule,
		java.lang.String _deliveryviaRule,
		java.lang.String _priorityRule,
		java.lang.String _isTaxincluded,
		java.lang.String _sendemail,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setDocno(_docno);
		this.setDocType(_docType);
		this.setTargetdocType(_targetdocType);
		this.setDescription(_description);
		this.setPaymentRule(_paymentRule);
		this.setInvoiceRule(_invoiceRule);
		this.setDeliveryRule(_deliveryRule);
		this.setFreightCostRule(_freightCostRule);
		this.setDeliveryviaRule(_deliveryviaRule);
		this.setPriorityRule(_priorityRule);
		this.setIsTaxincluded(_isTaxincluded);
		this.setSendemail(_sendemail);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: DOCNO
	 */
	public java.lang.String getDocno () {
		return _docno;
	}

	/**
	 * Set the value related to the column: DOCNO
	 * @param _docno the DOCNO value
	 */
	public void setDocno (java.lang.String _docno) {
		this._docno = _docno;
	}


	/**
	 * Return the value associated with the column: DOCTYPE
	 */
	public java.lang.String getDocType () {
		return _docType;
	}

	/**
	 * Set the value related to the column: DOCTYPE
	 * @param _docType the DOCTYPE value
	 */
	public void setDocType (java.lang.String _docType) {
		this._docType = _docType;
	}


	/**
	 * Return the value associated with the column: TARGETDOCTYPE
	 */
	public java.lang.String getTargetdocType () {
		return _targetdocType;
	}

	/**
	 * Set the value related to the column: TARGETDOCTYPE
	 * @param _targetdocType the TARGETDOCTYPE value
	 */
	public void setTargetdocType (java.lang.String _targetdocType) {
		this._targetdocType = _targetdocType;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: SALESREP_ID
	 */
	public java.lang.Integer getSalesrepId () {
		return _salesrepId;
	}

	/**
	 * Set the value related to the column: SALESREP_ID
	 * @param _salesrepId the SALESREP_ID value
	 */
	public void setSalesrepId (java.lang.Integer _salesrepId) {
		this._salesrepId = _salesrepId;
	}


	/**
	 * Return the value associated with the column: C_BPARTNER_ID
	 */
	public java.lang.Integer getCBpartnerId () {
		return _cBpartnerId;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartnerId the C_BPARTNER_ID value
	 */
	public void setCBpartnerId (java.lang.Integer _cBpartnerId) {
		this._cBpartnerId = _cBpartnerId;
	}


	/**
	 * Return the value associated with the column: C_BPARTNER_LOCATION_ID
	 */
	public java.lang.Integer getCBpartnerLocationId () {
		return _cBpartnerLocationId;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_LOCATION_ID
	 * @param _cBpartnerLocationId the C_BPARTNER_LOCATION_ID value
	 */
	public void setCBpartnerLocationId (java.lang.Integer _cBpartnerLocationId) {
		this._cBpartnerLocationId = _cBpartnerLocationId;
	}


	/**
	 * Return the value associated with the column: PAYMENTRULE
	 */
	public java.lang.String getPaymentRule () {
		return _paymentRule;
	}

	/**
	 * Set the value related to the column: PAYMENTRULE
	 * @param _paymentRule the PAYMENTRULE value
	 */
	public void setPaymentRule (java.lang.String _paymentRule) {
		this._paymentRule = _paymentRule;
	}


	/**
	 * Return the value associated with the column: INVOICERULE
	 */
	public java.lang.String getInvoiceRule () {
		return _invoiceRule;
	}

	/**
	 * Set the value related to the column: INVOICERULE
	 * @param _invoiceRule the INVOICERULE value
	 */
	public void setInvoiceRule (java.lang.String _invoiceRule) {
		this._invoiceRule = _invoiceRule;
	}


	/**
	 * Return the value associated with the column: DELIVERYRULE
	 */
	public java.lang.String getDeliveryRule () {
		return _deliveryRule;
	}

	/**
	 * Set the value related to the column: DELIVERYRULE
	 * @param _deliveryRule the DELIVERYRULE value
	 */
	public void setDeliveryRule (java.lang.String _deliveryRule) {
		this._deliveryRule = _deliveryRule;
	}


	/**
	 * Return the value associated with the column: FREIGHTCOSTRULE
	 */
	public java.lang.String getFreightCostRule () {
		return _freightCostRule;
	}

	/**
	 * Set the value related to the column: FREIGHTCOSTRULE
	 * @param _freightCostRule the FREIGHTCOSTRULE value
	 */
	public void setFreightCostRule (java.lang.String _freightCostRule) {
		this._freightCostRule = _freightCostRule;
	}


	/**
	 * Return the value associated with the column: FREIGHTAMT
	 */
	public double getFreightAmt () {
		return _freightAmt;
	}

	/**
	 * Set the value related to the column: FREIGHTAMT
	 * @param _freightAmt the FREIGHTAMT value
	 */
	public void setFreightAmt (double _freightAmt) {
		this._freightAmt = _freightAmt;
	}


	/**
	 * Return the value associated with the column: DELIVERYVIARULE
	 */
	public java.lang.String getDeliveryviaRule () {
		return _deliveryviaRule;
	}

	/**
	 * Set the value related to the column: DELIVERYVIARULE
	 * @param _deliveryviaRule the DELIVERYVIARULE value
	 */
	public void setDeliveryviaRule (java.lang.String _deliveryviaRule) {
		this._deliveryviaRule = _deliveryviaRule;
	}


	/**
	 * Return the value associated with the column: M_SHIPPER_ID
	 */
	public java.lang.Integer getMShipperId () {
		return _mShipperId;
	}

	/**
	 * Set the value related to the column: M_SHIPPER_ID
	 * @param _mShipperId the M_SHIPPER_ID value
	 */
	public void setMShipperId (java.lang.Integer _mShipperId) {
		this._mShipperId = _mShipperId;
	}


	/**
	 * Return the value associated with the column: C_CHARGE_ID
	 */
	public java.lang.Integer getCChargeId () {
		return _cChargeId;
	}

	/**
	 * Set the value related to the column: C_CHARGE_ID
	 * @param _cChargeId the C_CHARGE_ID value
	 */
	public void setCChargeId (java.lang.Integer _cChargeId) {
		this._cChargeId = _cChargeId;
	}


	/**
	 * Return the value associated with the column: CHARGEAMT
	 */
	public double getChargeAmt () {
		return _chargeAmt;
	}

	/**
	 * Set the value related to the column: CHARGEAMT
	 * @param _chargeAmt the CHARGEAMT value
	 */
	public void setChargeAmt (double _chargeAmt) {
		this._chargeAmt = _chargeAmt;
	}


	/**
	 * Return the value associated with the column: PRIORITYRULE
	 */
	public java.lang.String getPriorityRule () {
		return _priorityRule;
	}

	/**
	 * Set the value related to the column: PRIORITYRULE
	 * @param _priorityRule the PRIORITYRULE value
	 */
	public void setPriorityRule (java.lang.String _priorityRule) {
		this._priorityRule = _priorityRule;
	}


	/**
	 * Return the value associated with the column: M_WAREHOUSE_ID
	 */
	public java.lang.Integer getMWarehouseId () {
		return _mWarehouseId;
	}

	/**
	 * Set the value related to the column: M_WAREHOUSE_ID
	 * @param _mWarehouseId the M_WAREHOUSE_ID value
	 */
	public void setMWarehouseId (java.lang.Integer _mWarehouseId) {
		this._mWarehouseId = _mWarehouseId;
	}


	/**
	 * Return the value associated with the column: ISTAXINCLUDED
	 */
	public java.lang.String getIsTaxincluded () {
		return _isTaxincluded;
	}

	/**
	 * Set the value related to the column: ISTAXINCLUDED
	 * @param _isTaxincluded the ISTAXINCLUDED value
	 */
	public void setIsTaxincluded (java.lang.String _isTaxincluded) {
		this._isTaxincluded = _isTaxincluded;
	}


	/**
	 * Return the value associated with the column: C_PAYMENT_ID
	 */
	public java.lang.Integer getCPaymentId () {
		return _cPaymentId;
	}

	/**
	 * Set the value related to the column: C_PAYMENT_ID
	 * @param _cPaymentId the C_PAYMENT_ID value
	 */
	public void setCPaymentId (java.lang.Integer _cPaymentId) {
		this._cPaymentId = _cPaymentId;
	}


	/**
	 * Return the value associated with the column: SENDEMAIL
	 */
	public java.lang.String getSendemail () {
		return _sendemail;
	}

	/**
	 * Set the value related to the column: SENDEMAIL
	 * @param _sendemail the SENDEMAIL value
	 */
	public void setSendemail (java.lang.String _sendemail) {
		this._sendemail = _sendemail;
	}


	/**
	 * Return the value associated with the column: AD_USER_ID
	 */
	public java.lang.Integer getAdUserId () {
		return _adUserId;
	}

	/**
	 * Set the value related to the column: AD_USER_ID
	 * @param _adUserId the AD_USER_ID value
	 */
	public void setAdUserId (java.lang.Integer _adUserId) {
		this._adUserId = _adUserId;
	}


	/**
	 * Return the value associated with the column: BILL_BPARTNER_ID
	 */
	public java.lang.Integer getBillBpartnerId () {
		return _billBpartnerId;
	}

	/**
	 * Set the value related to the column: BILL_BPARTNER_ID
	 * @param _billBpartnerId the BILL_BPARTNER_ID value
	 */
	public void setBillBpartnerId (java.lang.Integer _billBpartnerId) {
		this._billBpartnerId = _billBpartnerId;
	}


	/**
	 * Return the value associated with the column: BILL_LOCATION_ID
	 */
	public java.lang.Integer getBillLocationId () {
		return _billLocationId;
	}

	/**
	 * Set the value related to the column: BILL_LOCATION_ID
	 * @param _billLocationId the BILL_LOCATION_ID value
	 */
	public void setBillLocationId (java.lang.Integer _billLocationId) {
		this._billLocationId = _billLocationId;
	}


	/**
	 * Return the value associated with the column: BILL_USER_ID
	 */
	public java.lang.Integer getBillUserId () {
		return _billUserId;
	}

	/**
	 * Set the value related to the column: BILL_USER_ID
	 * @param _billUserId the BILL_USER_ID value
	 */
	public void setBillUserId (java.lang.Integer _billUserId) {
		this._billUserId = _billUserId;
	}


	/**
	 * Return the value associated with the column: PAY_BPARTNER_ID
	 */
	public java.lang.Integer getPayBpartnerId () {
		return _payBpartnerId;
	}

	/**
	 * Set the value related to the column: PAY_BPARTNER_ID
	 * @param _payBpartnerId the PAY_BPARTNER_ID value
	 */
	public void setPayBpartnerId (java.lang.Integer _payBpartnerId) {
		this._payBpartnerId = _payBpartnerId;
	}


	/**
	 * Return the value associated with the column: PAY_LOCATION_ID
	 */
	public java.lang.Integer getPayLocationId () {
		return _payLocationId;
	}

	/**
	 * Set the value related to the column: PAY_LOCATION_ID
	 * @param _payLocationId the PAY_LOCATION_ID value
	 */
	public void setPayLocationId (java.lang.Integer _payLocationId) {
		this._payLocationId = _payLocationId;
	}


	/**
	 * Return the value associated with the column: REF_ORDER_ID
	 */
	public java.lang.Integer getRefOrderId () {
		return _refOrderId;
	}

	/**
	 * Set the value related to the column: REF_ORDER_ID
	 * @param _refOrderId the REF_ORDER_ID value
	 */
	public void setRefOrderId (java.lang.Integer _refOrderId) {
		this._refOrderId = _refOrderId;
	}


	/**
	 * Return the value associated with the column: REF_CROSSORDER_ID
	 */
	public java.lang.Integer getRefCrossorderId () {
		return _refCrossorderId;
	}

	/**
	 * Set the value related to the column: REF_CROSSORDER_ID
	 * @param _refCrossorderId the REF_CROSSORDER_ID value
	 */
	public void setRefCrossorderId (java.lang.Integer _refCrossorderId) {
		this._refCrossorderId = _refCrossorderId;
	}


	/**
	 * Return the value associated with the column: TOT_LINES
	 */
	public java.lang.Integer getTotLines () {
		return _totLines;
	}

	/**
	 * Set the value related to the column: TOT_LINES
	 * @param _totLines the TOT_LINES value
	 */
	public void setTotLines (java.lang.Integer _totLines) {
		this._totLines = _totLines;
	}


	/**
	 * Return the value associated with the column: TOT_QTY
	 */
	public java.lang.Integer getTotQty () {
		return _totQty;
	}

	/**
	 * Set the value related to the column: TOT_QTY
	 * @param _totQty the TOT_QTY value
	 */
	public void setTotQty (java.lang.Integer _totQty) {
		this._totQty = _totQty;
	}


	/**
	 * Return the value associated with the column: TOT_SUM
	 */
	public double getTotSum () {
		return _totSum;
	}

	/**
	 * Set the value related to the column: TOT_SUM
	 * @param _totSum the TOT_SUM value
	 */
	public void setTotSum (double _totSum) {
		this._totSum = _totSum;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=SALESREP_ID
	 */
	public nds.model.Users getSalesrep () {
		return this._salesrep;
	}

	/**
	 * Set the value related to the column: SALESREP_ID
	 * @param _salesrep the SALESREP_ID value
	 */
	public void setSalesrep (nds.model.Users _salesrep) {
		this._salesrep = _salesrep;
	}


	/**
     * @hibernate.property
     *  column=C_BPARTNER_ID
	 */
	public nds.model.CBpartner getCBpartner () {
		return this._cBpartner;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartner the C_BPARTNER_ID value
	 */
	public void setCBpartner (nds.model.CBpartner _cBpartner) {
		this._cBpartner = _cBpartner;
	}


	/**
     * @hibernate.property
     *  column=C_BPARTNER_LOCATION_ID
	 */
	public nds.model.CBpartnerLocation getCBpartnerLocation () {
		return this._cBpartnerLocation;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_LOCATION_ID
	 * @param _cBpartnerLocation the C_BPARTNER_LOCATION_ID value
	 */
	public void setCBpartnerLocation (nds.model.CBpartnerLocation _cBpartnerLocation) {
		this._cBpartnerLocation = _cBpartnerLocation;
	}


	/**
     * @hibernate.property
     *  column=M_SHIPPER_ID
	 */
	public nds.model.MShipper getMShipper () {
		return this._mShipper;
	}

	/**
	 * Set the value related to the column: M_SHIPPER_ID
	 * @param _mShipper the M_SHIPPER_ID value
	 */
	public void setMShipper (nds.model.MShipper _mShipper) {
		this._mShipper = _mShipper;
	}


	/**
     * @hibernate.property
     *  column=C_CHARGE_ID
	 */
	public nds.model.CCharge getCCharge () {
		return this._cCharge;
	}

	/**
	 * Set the value related to the column: C_CHARGE_ID
	 * @param _cCharge the C_CHARGE_ID value
	 */
	public void setCCharge (nds.model.CCharge _cCharge) {
		this._cCharge = _cCharge;
	}


	/**
     * @hibernate.property
     *  column=M_WAREHOUSE_ID
	 */
	public nds.model.MWarehouse getMWarehouse () {
		return this._mWarehouse;
	}

	/**
	 * Set the value related to the column: M_WAREHOUSE_ID
	 * @param _mWarehouse the M_WAREHOUSE_ID value
	 */
	public void setMWarehouse (nds.model.MWarehouse _mWarehouse) {
		this._mWarehouse = _mWarehouse;
	}


	/**
     * @hibernate.property
     *  column=C_PAYMENT_ID
	 */
	public nds.model.CPayment getCPayment () {
		return this._cPayment;
	}

	/**
	 * Set the value related to the column: C_PAYMENT_ID
	 * @param _cPayment the C_PAYMENT_ID value
	 */
	public void setCPayment (nds.model.CPayment _cPayment) {
		this._cPayment = _cPayment;
	}


	/**
     * @hibernate.property
     *  column=AD_USER_ID
	 */
	public nds.model.Users getAdUser () {
		return this._adUser;
	}

	/**
	 * Set the value related to the column: AD_USER_ID
	 * @param _adUser the AD_USER_ID value
	 */
	public void setAdUser (nds.model.Users _adUser) {
		this._adUser = _adUser;
	}


	/**
     * @hibernate.property
     *  column=BILL_BPARTNER_ID
	 */
	public nds.model.CBpartner getBillBpartner () {
		return this._billBpartner;
	}

	/**
	 * Set the value related to the column: BILL_BPARTNER_ID
	 * @param _billBpartner the BILL_BPARTNER_ID value
	 */
	public void setBillBpartner (nds.model.CBpartner _billBpartner) {
		this._billBpartner = _billBpartner;
	}


	/**
     * @hibernate.property
     *  column=BILL_LOCATION_ID
	 */
	public nds.model.CBpartnerLocation getBillLocation () {
		return this._billLocation;
	}

	/**
	 * Set the value related to the column: BILL_LOCATION_ID
	 * @param _billLocation the BILL_LOCATION_ID value
	 */
	public void setBillLocation (nds.model.CBpartnerLocation _billLocation) {
		this._billLocation = _billLocation;
	}


	/**
     * @hibernate.property
     *  column=BILL_USER_ID
	 */
	public nds.model.Users getBillUser () {
		return this._billUser;
	}

	/**
	 * Set the value related to the column: BILL_USER_ID
	 * @param _billUser the BILL_USER_ID value
	 */
	public void setBillUser (nds.model.Users _billUser) {
		this._billUser = _billUser;
	}


	/**
     * @hibernate.property
     *  column=PAY_BPARTNER_ID
	 */
	public nds.model.CBpartner getPayBpartner () {
		return this._payBpartner;
	}

	/**
	 * Set the value related to the column: PAY_BPARTNER_ID
	 * @param _payBpartner the PAY_BPARTNER_ID value
	 */
	public void setPayBpartner (nds.model.CBpartner _payBpartner) {
		this._payBpartner = _payBpartner;
	}


	/**
     * @hibernate.property
     *  column=PAY_LOCATION_ID
	 */
	public nds.model.CBpartnerLocation getPayLocation () {
		return this._payLocation;
	}

	/**
	 * Set the value related to the column: PAY_LOCATION_ID
	 * @param _payLocation the PAY_LOCATION_ID value
	 */
	public void setPayLocation (nds.model.CBpartnerLocation _payLocation) {
		this._payLocation = _payLocation;
	}


	/**
     * @hibernate.property
     *  column=REF_ORDER_ID
	 */
	public nds.model.COrder getRefOrder () {
		return this._refOrder;
	}

	/**
	 * Set the value related to the column: REF_ORDER_ID
	 * @param _refOrder the REF_ORDER_ID value
	 */
	public void setRefOrder (nds.model.COrder _refOrder) {
		this._refOrder = _refOrder;
	}


	/**
     * @hibernate.property
     *  column=REF_CROSSORDER_ID
	 */
	public nds.model.CCrossorder getRefCrossorder () {
		return this._refCrossorder;
	}

	/**
	 * Set the value related to the column: REF_CROSSORDER_ID
	 * @param _refCrossorder the REF_CROSSORDER_ID value
	 */
	public void setRefCrossorder (nds.model.CCrossorder _refCrossorder) {
		this._refCrossorder = _refCrossorder;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseCOrder)) return false;
		else {
			nds.model.base.BaseCOrder mObj = (nds.model.base.BaseCOrder) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}