package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the M_INOUTITEM table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="M_INOUTITEM"
 */
public abstract class BaseMInoutItem  implements Serializable {

	public static String PROP_M_PRODUCT_ID = "MProductId";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_M_PRODUCT = "MProduct";
	public static String PROP_M_LOCATOR_ID = "MLocatorId";
	public static String PROP_C_UOM = "CUom";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_MOVE_QTY = "MoveQty";
	public static String PROP_REF_INOUT_ITEM_ID = "RefInoutItemId";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_LINE = "Line";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_M_ATTRIBUTE_SET_INSTANCE_ID = "MAttributeSetInstanceId";
	public static String PROP_C_UOM_ID = "CUomId";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_M_INOUT = "MInout";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_REF_INOUT_ITEM = "RefInoutItem";
	public static String PROP_M_INOUT_ID = "MInoutId";
	public static String PROP_C_ORDERLINE = "COrderline";
	public static String PROP_M_ATTRIBUTE_SET_INSTANCE = "MAttributeSetInstance";
	public static String PROP_C_ORDERLINE_ID = "COrderlineId";
	public static String PROP_PLAN_QTY = "PlanQty";
	public static String PROP_DIFF_QTY = "DiffQty";
	public static String PROP_M_LOCATOR = "MLocator";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.Integer _mInoutId;
	private java.lang.Integer _line;
	private java.lang.String _description;
	private java.lang.Integer _mProductId;
	private java.lang.Integer _mAttributeSetInstanceId;
	private java.lang.Integer _cUomId;
	private java.lang.Integer _mLocatorId;
	private java.lang.Integer _refInoutItemId;
	private java.lang.Integer _cOrderlineId;
	private java.lang.Integer _planQty;
	private java.lang.Integer _moveQty;
	private java.lang.Integer _diffQty;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.MInout _mInout;
	private nds.model.MProduct _mProduct;
	private nds.model.MAttributeSetInstance _mAttributeSetInstance;
	private nds.model.CUom _cUom;
	private nds.model.MLocator _mLocator;
	private nds.model.MInoutItem _refInoutItem;
	private nds.model.COrderItem _cOrderline;


	// constructors
	public BaseMInoutItem () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMInoutItem (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseMInoutItem (
		java.lang.Integer _id,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: M_INOUT_ID
	 */
	public java.lang.Integer getMInoutId () {
		return _mInoutId;
	}

	/**
	 * Set the value related to the column: M_INOUT_ID
	 * @param _mInoutId the M_INOUT_ID value
	 */
	public void setMInoutId (java.lang.Integer _mInoutId) {
		this._mInoutId = _mInoutId;
	}


	/**
	 * Return the value associated with the column: LINE
	 */
	public java.lang.Integer getLine () {
		return _line;
	}

	/**
	 * Set the value related to the column: LINE
	 * @param _line the LINE value
	 */
	public void setLine (java.lang.Integer _line) {
		this._line = _line;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: M_PRODUCT_ID
	 */
	public java.lang.Integer getMProductId () {
		return _mProductId;
	}

	/**
	 * Set the value related to the column: M_PRODUCT_ID
	 * @param _mProductId the M_PRODUCT_ID value
	 */
	public void setMProductId (java.lang.Integer _mProductId) {
		this._mProductId = _mProductId;
	}


	/**
	 * Return the value associated with the column: M_ATTRIBUTESETINSTANCE_ID
	 */
	public java.lang.Integer getMAttributeSetInstanceId () {
		return _mAttributeSetInstanceId;
	}

	/**
	 * Set the value related to the column: M_ATTRIBUTESETINSTANCE_ID
	 * @param _mAttributeSetInstanceId the M_ATTRIBUTESETINSTANCE_ID value
	 */
	public void setMAttributeSetInstanceId (java.lang.Integer _mAttributeSetInstanceId) {
		this._mAttributeSetInstanceId = _mAttributeSetInstanceId;
	}


	/**
	 * Return the value associated with the column: C_UOM_ID
	 */
	public java.lang.Integer getCUomId () {
		return _cUomId;
	}

	/**
	 * Set the value related to the column: C_UOM_ID
	 * @param _cUomId the C_UOM_ID value
	 */
	public void setCUomId (java.lang.Integer _cUomId) {
		this._cUomId = _cUomId;
	}


	/**
	 * Return the value associated with the column: M_LOCATOR_ID
	 */
	public java.lang.Integer getMLocatorId () {
		return _mLocatorId;
	}

	/**
	 * Set the value related to the column: M_LOCATOR_ID
	 * @param _mLocatorId the M_LOCATOR_ID value
	 */
	public void setMLocatorId (java.lang.Integer _mLocatorId) {
		this._mLocatorId = _mLocatorId;
	}


	/**
	 * Return the value associated with the column: REF_INOUTITEM_ID
	 */
	public java.lang.Integer getRefInoutItemId () {
		return _refInoutItemId;
	}

	/**
	 * Set the value related to the column: REF_INOUTITEM_ID
	 * @param _refInoutItemId the REF_INOUTITEM_ID value
	 */
	public void setRefInoutItemId (java.lang.Integer _refInoutItemId) {
		this._refInoutItemId = _refInoutItemId;
	}


	/**
	 * Return the value associated with the column: C_ORDERLINE_ID
	 */
	public java.lang.Integer getCOrderlineId () {
		return _cOrderlineId;
	}

	/**
	 * Set the value related to the column: C_ORDERLINE_ID
	 * @param _cOrderlineId the C_ORDERLINE_ID value
	 */
	public void setCOrderlineId (java.lang.Integer _cOrderlineId) {
		this._cOrderlineId = _cOrderlineId;
	}


	/**
	 * Return the value associated with the column: PLAN_QTY
	 */
	public java.lang.Integer getPlanQty () {
		return _planQty;
	}

	/**
	 * Set the value related to the column: PLAN_QTY
	 * @param _planQty the PLAN_QTY value
	 */
	public void setPlanQty (java.lang.Integer _planQty) {
		this._planQty = _planQty;
	}


	/**
	 * Return the value associated with the column: MOVE_QTY
	 */
	public java.lang.Integer getMoveQty () {
		return _moveQty;
	}

	/**
	 * Set the value related to the column: MOVE_QTY
	 * @param _moveQty the MOVE_QTY value
	 */
	public void setMoveQty (java.lang.Integer _moveQty) {
		this._moveQty = _moveQty;
	}


	/**
	 * Return the value associated with the column: DIFF_QTY
	 */
	public java.lang.Integer getDiffQty () {
		return _diffQty;
	}

	/**
	 * Set the value related to the column: DIFF_QTY
	 * @param _diffQty the DIFF_QTY value
	 */
	public void setDiffQty (java.lang.Integer _diffQty) {
		this._diffQty = _diffQty;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=M_INOUT_ID
	 */
	public nds.model.MInout getMInout () {
		return this._mInout;
	}

	/**
	 * Set the value related to the column: M_INOUT_ID
	 * @param _mInout the M_INOUT_ID value
	 */
	public void setMInout (nds.model.MInout _mInout) {
		this._mInout = _mInout;
	}


	/**
     * @hibernate.property
     *  column=M_PRODUCT_ID
	 */
	public nds.model.MProduct getMProduct () {
		return this._mProduct;
	}

	/**
	 * Set the value related to the column: M_PRODUCT_ID
	 * @param _mProduct the M_PRODUCT_ID value
	 */
	public void setMProduct (nds.model.MProduct _mProduct) {
		this._mProduct = _mProduct;
	}


	/**
     * @hibernate.property
     *  column=M_ATTRIBUTESETINSTANCE_ID
	 */
	public nds.model.MAttributeSetInstance getMAttributeSetInstance () {
		return this._mAttributeSetInstance;
	}

	/**
	 * Set the value related to the column: M_ATTRIBUTESETINSTANCE_ID
	 * @param _mAttributeSetInstance the M_ATTRIBUTESETINSTANCE_ID value
	 */
	public void setMAttributeSetInstance (nds.model.MAttributeSetInstance _mAttributeSetInstance) {
		this._mAttributeSetInstance = _mAttributeSetInstance;
	}


	/**
     * @hibernate.property
     *  column=C_UOM_ID
	 */
	public nds.model.CUom getCUom () {
		return this._cUom;
	}

	/**
	 * Set the value related to the column: C_UOM_ID
	 * @param _cUom the C_UOM_ID value
	 */
	public void setCUom (nds.model.CUom _cUom) {
		this._cUom = _cUom;
	}


	/**
     * @hibernate.property
     *  column=M_LOCATOR_ID
	 */
	public nds.model.MLocator getMLocator () {
		return this._mLocator;
	}

	/**
	 * Set the value related to the column: M_LOCATOR_ID
	 * @param _mLocator the M_LOCATOR_ID value
	 */
	public void setMLocator (nds.model.MLocator _mLocator) {
		this._mLocator = _mLocator;
	}


	/**
     * @hibernate.property
     *  column=REF_INOUTITEM_ID
	 */
	public nds.model.MInoutItem getRefInoutItem () {
		return this._refInoutItem;
	}

	/**
	 * Set the value related to the column: REF_INOUTITEM_ID
	 * @param _refInoutItem the REF_INOUTITEM_ID value
	 */
	public void setRefInoutItem (nds.model.MInoutItem _refInoutItem) {
		this._refInoutItem = _refInoutItem;
	}


	/**
     * @hibernate.property
     *  column=C_ORDERLINE_ID
	 */
	public nds.model.COrderItem getCOrderline () {
		return this._cOrderline;
	}

	/**
	 * Set the value related to the column: C_ORDERLINE_ID
	 * @param _cOrderline the C_ORDERLINE_ID value
	 */
	public void setCOrderline (nds.model.COrderItem _cOrderline) {
		this._cOrderline = _cOrderline;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseMInoutItem)) return false;
		else {
			nds.model.base.BaseMInoutItem mObj = (nds.model.base.BaseMInoutItem) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}