package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the M_INOUT table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="M_INOUT"
 */
public abstract class BaseMInout  implements Serializable {

	public static String PROP_STATUS = "Status";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_M_SHIPPER = "MShipper";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_DELIVERY_RULE = "DeliveryRule";
	public static String PROP_C_INVOICE = "CInvoice";
	public static String PROP_PRIORITY_RULE = "PriorityRule";
	public static String PROP_MOVEMENT_TYPE = "MovementType";
	public static String PROP_M_WAREHOUSE = "MWarehouse";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_FREIGHT_COST_RULE = "FreightCostRule";
	public static String PROP_DATE_ACCT = "DateAcct";
	public static String PROP_MOVEMENT_DATE = "MovementDate";
	public static String PROP_CHARGE_AMT = "ChargeAmt";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_DOCNO = "Docno";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_REF_INOUT_ID = "RefInoutId";
	public static String PROP_C_ORDER = "COrder";
	public static String PROP_C_CHARGE_ID = "CChargeId";
	public static String PROP_DOC_TYPE = "DocType";
	public static String PROP_C_BPARTNER_ID = "CBpartnerId";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_TARGETDOC_TYPE = "TargetdocType";
	public static String PROP_DELIVERYVIA_RULE = "DeliveryviaRule";
	public static String PROP_SALESREP_ID = "SalesrepId";
	public static String PROP_C_BPARTNER_LOCATION_ID = "CBpartnerLocationId";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_FREIGHT_AMT = "FreightAmt";
	public static String PROP_SALESREP = "Salesrep";
	public static String PROP_M_WAREHOUSE_ID = "MWarehouseId";
	public static String PROP_TOT_MOVE_QTY = "TotMoveQty";
	public static String PROP_C_BPARTNER = "CBpartner";
	public static String PROP_M_SHIPPER_ID = "MShipperId";
	public static String PROP_C_BPARTNER_LOCATION = "CBpartnerLocation";
	public static String PROP_DATE_ORDERED = "DateOrdered";
	public static String PROP_REF_INOUT = "RefInout";
	public static String PROP_C_CHARGE = "CCharge";
	public static String PROP_TOT_DIFF_QTY = "TotDiffQty";
	public static String PROP_C_INVOICE_ID = "CInvoiceId";
	public static String PROP_TOT_PLAN_QTY = "TotPlanQty";
	public static String PROP_ID = "Id";
	public static String PROP_C_ORDER_ID = "COrderId";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _docno;
	private java.lang.String _docType;
	private java.lang.String _targetdocType;
	private java.lang.String _movementType;
	private java.lang.Integer _cOrderId;
	private java.util.Date _dateOrdered;
	private java.lang.String _description;
	private java.lang.Integer _salesrepId;
	private java.util.Date _movementDate;
	private java.util.Date _dateAcct;
	private java.lang.Integer _cBpartnerId;
	private java.lang.Integer _cBpartnerLocationId;
	private java.lang.Integer _cInvoiceId;
	private java.lang.String _deliveryRule;
	private java.lang.String _freightCostRule;
	private double _freightAmt;
	private java.lang.String _deliveryviaRule;
	private java.lang.Integer _mShipperId;
	private java.lang.Integer _cChargeId;
	private double _chargeAmt;
	private java.lang.String _priorityRule;
	private java.lang.Integer _mWarehouseId;
	private java.lang.Integer _totPlanQty;
	private java.lang.Integer _totMoveQty;
	private java.lang.Integer _totDiffQty;
	private java.lang.Integer _refInoutId;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;
	private java.lang.Integer _status;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.COrder _cOrder;
	private nds.model.Users _salesrep;
	private nds.model.CBpartner _cBpartner;
	private nds.model.CBpartnerLocation _cBpartnerLocation;
	private nds.model.CInvoice _cInvoice;
	private nds.model.MShipper _mShipper;
	private nds.model.CCharge _cCharge;
	private nds.model.MWarehouse _mWarehouse;
	private nds.model.MInout _refInout;


	// constructors
	public BaseMInout () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseMInout (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseMInout (
		java.lang.Integer _id,
		java.lang.String _docno,
		java.lang.String _docType,
		java.lang.String _targetdocType,
		java.lang.String _movementType,
		java.lang.String _description,
		java.lang.String _deliveryRule,
		java.lang.String _freightCostRule,
		java.lang.String _deliveryviaRule,
		java.lang.String _priorityRule,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setDocno(_docno);
		this.setDocType(_docType);
		this.setTargetdocType(_targetdocType);
		this.setMovementType(_movementType);
		this.setDescription(_description);
		this.setDeliveryRule(_deliveryRule);
		this.setFreightCostRule(_freightCostRule);
		this.setDeliveryviaRule(_deliveryviaRule);
		this.setPriorityRule(_priorityRule);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: DOCNO
	 */
	public java.lang.String getDocno () {
		return _docno;
	}

	/**
	 * Set the value related to the column: DOCNO
	 * @param _docno the DOCNO value
	 */
	public void setDocno (java.lang.String _docno) {
		this._docno = _docno;
	}


	/**
	 * Return the value associated with the column: DOCTYPE
	 */
	public java.lang.String getDocType () {
		return _docType;
	}

	/**
	 * Set the value related to the column: DOCTYPE
	 * @param _docType the DOCTYPE value
	 */
	public void setDocType (java.lang.String _docType) {
		this._docType = _docType;
	}


	/**
	 * Return the value associated with the column: TARGETDOCTYPE
	 */
	public java.lang.String getTargetdocType () {
		return _targetdocType;
	}

	/**
	 * Set the value related to the column: TARGETDOCTYPE
	 * @param _targetdocType the TARGETDOCTYPE value
	 */
	public void setTargetdocType (java.lang.String _targetdocType) {
		this._targetdocType = _targetdocType;
	}


	/**
	 * Return the value associated with the column: MOVEMENTTYPE
	 */
	public java.lang.String getMovementType () {
		return _movementType;
	}

	/**
	 * Set the value related to the column: MOVEMENTTYPE
	 * @param _movementType the MOVEMENTTYPE value
	 */
	public void setMovementType (java.lang.String _movementType) {
		this._movementType = _movementType;
	}


	/**
	 * Return the value associated with the column: C_ORDER_ID
	 */
	public java.lang.Integer getCOrderId () {
		return _cOrderId;
	}

	/**
	 * Set the value related to the column: C_ORDER_ID
	 * @param _cOrderId the C_ORDER_ID value
	 */
	public void setCOrderId (java.lang.Integer _cOrderId) {
		this._cOrderId = _cOrderId;
	}


	/**
	 * Return the value associated with the column: DATEORDERED
	 */
	public java.util.Date getDateOrdered () {
		return _dateOrdered;
	}

	/**
	 * Set the value related to the column: DATEORDERED
	 * @param _dateOrdered the DATEORDERED value
	 */
	public void setDateOrdered (java.util.Date _dateOrdered) {
		this._dateOrdered = _dateOrdered;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: SALESREP_ID
	 */
	public java.lang.Integer getSalesrepId () {
		return _salesrepId;
	}

	/**
	 * Set the value related to the column: SALESREP_ID
	 * @param _salesrepId the SALESREP_ID value
	 */
	public void setSalesrepId (java.lang.Integer _salesrepId) {
		this._salesrepId = _salesrepId;
	}


	/**
	 * Return the value associated with the column: MOVEMENTDATE
	 */
	public java.util.Date getMovementDate () {
		return _movementDate;
	}

	/**
	 * Set the value related to the column: MOVEMENTDATE
	 * @param _movementDate the MOVEMENTDATE value
	 */
	public void setMovementDate (java.util.Date _movementDate) {
		this._movementDate = _movementDate;
	}


	/**
	 * Return the value associated with the column: DATEACCT
	 */
	public java.util.Date getDateAcct () {
		return _dateAcct;
	}

	/**
	 * Set the value related to the column: DATEACCT
	 * @param _dateAcct the DATEACCT value
	 */
	public void setDateAcct (java.util.Date _dateAcct) {
		this._dateAcct = _dateAcct;
	}


	/**
	 * Return the value associated with the column: C_BPARTNER_ID
	 */
	public java.lang.Integer getCBpartnerId () {
		return _cBpartnerId;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartnerId the C_BPARTNER_ID value
	 */
	public void setCBpartnerId (java.lang.Integer _cBpartnerId) {
		this._cBpartnerId = _cBpartnerId;
	}


	/**
	 * Return the value associated with the column: C_BPARTNER_LOCATION_ID
	 */
	public java.lang.Integer getCBpartnerLocationId () {
		return _cBpartnerLocationId;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_LOCATION_ID
	 * @param _cBpartnerLocationId the C_BPARTNER_LOCATION_ID value
	 */
	public void setCBpartnerLocationId (java.lang.Integer _cBpartnerLocationId) {
		this._cBpartnerLocationId = _cBpartnerLocationId;
	}


	/**
	 * Return the value associated with the column: C_INVOICE_ID
	 */
	public java.lang.Integer getCInvoiceId () {
		return _cInvoiceId;
	}

	/**
	 * Set the value related to the column: C_INVOICE_ID
	 * @param _cInvoiceId the C_INVOICE_ID value
	 */
	public void setCInvoiceId (java.lang.Integer _cInvoiceId) {
		this._cInvoiceId = _cInvoiceId;
	}


	/**
	 * Return the value associated with the column: DELIVERYRULE
	 */
	public java.lang.String getDeliveryRule () {
		return _deliveryRule;
	}

	/**
	 * Set the value related to the column: DELIVERYRULE
	 * @param _deliveryRule the DELIVERYRULE value
	 */
	public void setDeliveryRule (java.lang.String _deliveryRule) {
		this._deliveryRule = _deliveryRule;
	}


	/**
	 * Return the value associated with the column: FREIGHTCOSTRULE
	 */
	public java.lang.String getFreightCostRule () {
		return _freightCostRule;
	}

	/**
	 * Set the value related to the column: FREIGHTCOSTRULE
	 * @param _freightCostRule the FREIGHTCOSTRULE value
	 */
	public void setFreightCostRule (java.lang.String _freightCostRule) {
		this._freightCostRule = _freightCostRule;
	}


	/**
	 * Return the value associated with the column: FREIGHTAMT
	 */
	public double getFreightAmt () {
		return _freightAmt;
	}

	/**
	 * Set the value related to the column: FREIGHTAMT
	 * @param _freightAmt the FREIGHTAMT value
	 */
	public void setFreightAmt (double _freightAmt) {
		this._freightAmt = _freightAmt;
	}


	/**
	 * Return the value associated with the column: DELIVERYVIARULE
	 */
	public java.lang.String getDeliveryviaRule () {
		return _deliveryviaRule;
	}

	/**
	 * Set the value related to the column: DELIVERYVIARULE
	 * @param _deliveryviaRule the DELIVERYVIARULE value
	 */
	public void setDeliveryviaRule (java.lang.String _deliveryviaRule) {
		this._deliveryviaRule = _deliveryviaRule;
	}


	/**
	 * Return the value associated with the column: M_SHIPPER_ID
	 */
	public java.lang.Integer getMShipperId () {
		return _mShipperId;
	}

	/**
	 * Set the value related to the column: M_SHIPPER_ID
	 * @param _mShipperId the M_SHIPPER_ID value
	 */
	public void setMShipperId (java.lang.Integer _mShipperId) {
		this._mShipperId = _mShipperId;
	}


	/**
	 * Return the value associated with the column: C_CHARGE_ID
	 */
	public java.lang.Integer getCChargeId () {
		return _cChargeId;
	}

	/**
	 * Set the value related to the column: C_CHARGE_ID
	 * @param _cChargeId the C_CHARGE_ID value
	 */
	public void setCChargeId (java.lang.Integer _cChargeId) {
		this._cChargeId = _cChargeId;
	}


	/**
	 * Return the value associated with the column: CHARGEAMT
	 */
	public double getChargeAmt () {
		return _chargeAmt;
	}

	/**
	 * Set the value related to the column: CHARGEAMT
	 * @param _chargeAmt the CHARGEAMT value
	 */
	public void setChargeAmt (double _chargeAmt) {
		this._chargeAmt = _chargeAmt;
	}


	/**
	 * Return the value associated with the column: PRIORITYRULE
	 */
	public java.lang.String getPriorityRule () {
		return _priorityRule;
	}

	/**
	 * Set the value related to the column: PRIORITYRULE
	 * @param _priorityRule the PRIORITYRULE value
	 */
	public void setPriorityRule (java.lang.String _priorityRule) {
		this._priorityRule = _priorityRule;
	}


	/**
	 * Return the value associated with the column: M_WAREHOUSE_ID
	 */
	public java.lang.Integer getMWarehouseId () {
		return _mWarehouseId;
	}

	/**
	 * Set the value related to the column: M_WAREHOUSE_ID
	 * @param _mWarehouseId the M_WAREHOUSE_ID value
	 */
	public void setMWarehouseId (java.lang.Integer _mWarehouseId) {
		this._mWarehouseId = _mWarehouseId;
	}


	/**
	 * Return the value associated with the column: TOT_PLAN_QTY
	 */
	public java.lang.Integer getTotPlanQty () {
		return _totPlanQty;
	}

	/**
	 * Set the value related to the column: TOT_PLAN_QTY
	 * @param _totPlanQty the TOT_PLAN_QTY value
	 */
	public void setTotPlanQty (java.lang.Integer _totPlanQty) {
		this._totPlanQty = _totPlanQty;
	}


	/**
	 * Return the value associated with the column: TOT_MOVE_QTY
	 */
	public java.lang.Integer getTotMoveQty () {
		return _totMoveQty;
	}

	/**
	 * Set the value related to the column: TOT_MOVE_QTY
	 * @param _totMoveQty the TOT_MOVE_QTY value
	 */
	public void setTotMoveQty (java.lang.Integer _totMoveQty) {
		this._totMoveQty = _totMoveQty;
	}


	/**
	 * Return the value associated with the column: TOT_DIFF_QTY
	 */
	public java.lang.Integer getTotDiffQty () {
		return _totDiffQty;
	}

	/**
	 * Set the value related to the column: TOT_DIFF_QTY
	 * @param _totDiffQty the TOT_DIFF_QTY value
	 */
	public void setTotDiffQty (java.lang.Integer _totDiffQty) {
		this._totDiffQty = _totDiffQty;
	}


	/**
	 * Return the value associated with the column: REF_INOUT_ID
	 */
	public java.lang.Integer getRefInoutId () {
		return _refInoutId;
	}

	/**
	 * Set the value related to the column: REF_INOUT_ID
	 * @param _refInoutId the REF_INOUT_ID value
	 */
	public void setRefInoutId (java.lang.Integer _refInoutId) {
		this._refInoutId = _refInoutId;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
	 * Return the value associated with the column: STATUS
	 */
	public java.lang.Integer getStatus () {
		return _status;
	}

	/**
	 * Set the value related to the column: STATUS
	 * @param _status the STATUS value
	 */
	public void setStatus (java.lang.Integer _status) {
		this._status = _status;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=C_ORDER_ID
	 */
	public nds.model.COrder getCOrder () {
		return this._cOrder;
	}

	/**
	 * Set the value related to the column: C_ORDER_ID
	 * @param _cOrder the C_ORDER_ID value
	 */
	public void setCOrder (nds.model.COrder _cOrder) {
		this._cOrder = _cOrder;
	}


	/**
     * @hibernate.property
     *  column=SALESREP_ID
	 */
	public nds.model.Users getSalesrep () {
		return this._salesrep;
	}

	/**
	 * Set the value related to the column: SALESREP_ID
	 * @param _salesrep the SALESREP_ID value
	 */
	public void setSalesrep (nds.model.Users _salesrep) {
		this._salesrep = _salesrep;
	}


	/**
     * @hibernate.property
     *  column=C_BPARTNER_ID
	 */
	public nds.model.CBpartner getCBpartner () {
		return this._cBpartner;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_ID
	 * @param _cBpartner the C_BPARTNER_ID value
	 */
	public void setCBpartner (nds.model.CBpartner _cBpartner) {
		this._cBpartner = _cBpartner;
	}


	/**
     * @hibernate.property
     *  column=C_BPARTNER_LOCATION_ID
	 */
	public nds.model.CBpartnerLocation getCBpartnerLocation () {
		return this._cBpartnerLocation;
	}

	/**
	 * Set the value related to the column: C_BPARTNER_LOCATION_ID
	 * @param _cBpartnerLocation the C_BPARTNER_LOCATION_ID value
	 */
	public void setCBpartnerLocation (nds.model.CBpartnerLocation _cBpartnerLocation) {
		this._cBpartnerLocation = _cBpartnerLocation;
	}


	/**
     * @hibernate.property
     *  column=C_INVOICE_ID
	 */
	public nds.model.CInvoice getCInvoice () {
		return this._cInvoice;
	}

	/**
	 * Set the value related to the column: C_INVOICE_ID
	 * @param _cInvoice the C_INVOICE_ID value
	 */
	public void setCInvoice (nds.model.CInvoice _cInvoice) {
		this._cInvoice = _cInvoice;
	}


	/**
     * @hibernate.property
     *  column=M_SHIPPER_ID
	 */
	public nds.model.MShipper getMShipper () {
		return this._mShipper;
	}

	/**
	 * Set the value related to the column: M_SHIPPER_ID
	 * @param _mShipper the M_SHIPPER_ID value
	 */
	public void setMShipper (nds.model.MShipper _mShipper) {
		this._mShipper = _mShipper;
	}


	/**
     * @hibernate.property
     *  column=C_CHARGE_ID
	 */
	public nds.model.CCharge getCCharge () {
		return this._cCharge;
	}

	/**
	 * Set the value related to the column: C_CHARGE_ID
	 * @param _cCharge the C_CHARGE_ID value
	 */
	public void setCCharge (nds.model.CCharge _cCharge) {
		this._cCharge = _cCharge;
	}


	/**
     * @hibernate.property
     *  column=M_WAREHOUSE_ID
	 */
	public nds.model.MWarehouse getMWarehouse () {
		return this._mWarehouse;
	}

	/**
	 * Set the value related to the column: M_WAREHOUSE_ID
	 * @param _mWarehouse the M_WAREHOUSE_ID value
	 */
	public void setMWarehouse (nds.model.MWarehouse _mWarehouse) {
		this._mWarehouse = _mWarehouse;
	}


	/**
     * @hibernate.property
     *  column=REF_INOUT_ID
	 */
	public nds.model.MInout getRefInout () {
		return this._refInout;
	}

	/**
	 * Set the value related to the column: REF_INOUT_ID
	 * @param _refInout the REF_INOUT_ID value
	 */
	public void setRefInout (nds.model.MInout _refInout) {
		this._refInout = _refInout;
	}


	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseMInout)) return false;
		else {
			nds.model.base.BaseMInout mObj = (nds.model.base.BaseMInout) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}