package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the C_COUNTRY table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="C_COUNTRY"
 */
public abstract class BaseCCountry  implements Serializable {

	public static String PROP_C_CURRENCY = "CCurrency";
	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_AD_LANGUAGE = "AdLanguage";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_C_CURRENCY_ID = "CCurrencyId";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_COUNTRYCODE = "Countrycode";
	public static String PROP_REGION_NAME = "RegionName";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_NAME = "Name";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _name;
	private java.lang.String _description;
	private java.lang.String _countrycode;
	private java.lang.String _regionName;
	private java.lang.String _adLanguage;
	private java.lang.Integer _cCurrencyId;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.CCurrency _cCurrency;

	// collections
	private java.util.Set _cRegionSet;
	private java.util.Set _cCitySet;


	// constructors
	public BaseCCountry () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCCountry (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCCountry (
		java.lang.Integer _id,
		java.lang.String _name,
		java.lang.String _countrycode,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setName(_name);
		this.setCountrycode(_countrycode);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: NAME
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: NAME
	 * @param _name the NAME value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: COUNTRYCODE
	 */
	public java.lang.String getCountrycode () {
		return _countrycode;
	}

	/**
	 * Set the value related to the column: COUNTRYCODE
	 * @param _countrycode the COUNTRYCODE value
	 */
	public void setCountrycode (java.lang.String _countrycode) {
		this._countrycode = _countrycode;
	}


	/**
	 * Return the value associated with the column: REGIONNAME
	 */
	public java.lang.String getRegionName () {
		return _regionName;
	}

	/**
	 * Set the value related to the column: REGIONNAME
	 * @param _regionName the REGIONNAME value
	 */
	public void setRegionName (java.lang.String _regionName) {
		this._regionName = _regionName;
	}


	/**
	 * Return the value associated with the column: AD_LANGUAGE
	 */
	public java.lang.String getAdLanguage () {
		return _adLanguage;
	}

	/**
	 * Set the value related to the column: AD_LANGUAGE
	 * @param _adLanguage the AD_LANGUAGE value
	 */
	public void setAdLanguage (java.lang.String _adLanguage) {
		this._adLanguage = _adLanguage;
	}


	/**
	 * Return the value associated with the column: C_CURRENCY_ID
	 */
	public java.lang.Integer getCCurrencyId () {
		return _cCurrencyId;
	}

	/**
	 * Set the value related to the column: C_CURRENCY_ID
	 * @param _cCurrencyId the C_CURRENCY_ID value
	 */
	public void setCCurrencyId (java.lang.Integer _cCurrencyId) {
		this._cCurrencyId = _cCurrencyId;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=C_CURRENCY_ID
	 */
	public nds.model.CCurrency getCCurrency () {
		return this._cCurrency;
	}

	/**
	 * Set the value related to the column: C_CURRENCY_ID
	 * @param _cCurrency the C_CURRENCY_ID value
	 */
	public void setCCurrency (nds.model.CCurrency _cCurrency) {
		this._cCurrency = _cCurrency;
	}


	/**
	 * Return the value associated with the column: CRegionSet
	 */
	public java.util.Set getCRegionSet () {
		return this._cRegionSet;
	}

	/**
	 * Set the value related to the column: CRegionSet
	 * @param _cRegionSet the CRegionSet value
	 */
	public void setCRegionSet (java.util.Set _cRegionSet) {
		this._cRegionSet = _cRegionSet;
	}
	
	public void addToCRegionSet (Object obj) {
		if (null == this._cRegionSet) this._cRegionSet = new java.util.HashSet();
		this._cRegionSet.add(obj);
	}



	/**
	 * Return the value associated with the column: CCitySet
	 */
	public java.util.Set getCCitySet () {
		return this._cCitySet;
	}

	/**
	 * Set the value related to the column: CCitySet
	 * @param _cCitySet the CCitySet value
	 */
	public void setCCitySet (java.util.Set _cCitySet) {
		this._cCitySet = _cCitySet;
	}
	
	public void addToCCitySet (Object obj) {
		if (null == this._cCitySet) this._cCitySet = new java.util.HashSet();
		this._cCitySet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseCCountry)) return false;
		else {
			nds.model.base.BaseCCountry mObj = (nds.model.base.BaseCCountry) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}