package nds.model.base;

import java.io.Serializable;


/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is an object that contains data related to the C_BPARTNER table.
 * Do not modify this class because it will be overwritten if the configuration file
 * related to this class is modified.
 *
 * @hibernate.class
 *  table="C_BPARTNER"
 */
public abstract class BaseCBpartner  implements Serializable {

	public static String PROP_IS_ACTIVE = "IsActive";
	public static String PROP_AD_ORG = "AdOrg";
	public static String PROP_MODIFIER_ID = "ModifierId";
	public static String PROP_IS_CUSTOMER = "IsCustomer";
	public static String PROP_IS_EMPLOYEE = "IsEmployee";
	public static String PROP_OWNER_ID = "OwnerId";
	public static String PROP_C_BP_GROUP = "CBpGroup";
	public static String PROP_C_BP_GROUP_ID = "CBpGroupId";
	public static String PROP_AD_ORG_ID = "AdOrgId";
	public static String PROP_DESCRIPTION = "Description";
	public static String PROP_AD_CLIENT_ID = "AdClientId";
	public static String PROP_IS_SUMMARY = "IsSummary";
	public static String PROP_IS_VENDOR = "IsVendor";
	public static String PROP_NAME = "Name";
	public static String PROP_MODIFIED_DATE = "ModifiedDate";
	public static String PROP_ID = "Id";
	public static String PROP_CREATION_DATE = "CreationDate";


	private int hashCode = Integer.MIN_VALUE;

	// primary key
	private java.lang.Integer _id;

	// fields
	private java.lang.Integer _adClientId;
	private java.lang.Integer _adOrgId;
	private java.lang.String _name;
	private java.lang.String _description;
	private java.lang.String _isSummary;
	private java.lang.Integer _cBpGroupId;
	private java.lang.String _isVendor;
	private java.lang.String _isCustomer;
	private java.lang.String _isEmployee;
	private java.lang.Integer _ownerId;
	private java.lang.Integer _modifierId;
	private java.util.Date _creationDate;
	private java.util.Date _modifiedDate;
	private java.lang.String _isActive;

	// many to one
	private nds.model.AdOrg _adOrg;
	private nds.model.CBpGroup _cBpGroup;

	// collections
	private java.util.Set _cBpartnerLocationSet;
	private java.util.Set _cBpBankAccountSet;
	private java.util.Set _usersSet;


	// constructors
	public BaseCBpartner () {
		initialize();
	}

	/**
	 * Constructor for primary key
	 */
	public BaseCBpartner (java.lang.Integer _id) {
		this.setId(_id);
		initialize();
	}

	/**
	 * Constructor for required fields
	 */
	public BaseCBpartner (
		java.lang.Integer _id,
		java.lang.String _name,
		java.lang.String _description,
		java.lang.String _isSummary,
		java.lang.String _isVendor,
		java.lang.String _isCustomer,
		java.lang.String _isEmployee,
		java.lang.String _isActive) {

		this.setId(_id);
		this.setName(_name);
		this.setDescription(_description);
		this.setIsSummary(_isSummary);
		this.setIsVendor(_isVendor);
		this.setIsCustomer(_isCustomer);
		this.setIsEmployee(_isEmployee);
		this.setIsActive(_isActive);
		initialize();
	}

	protected void initialize () {}



	/**
	 * Return the unique identifier of this class
     * @hibernate.id
     *  generator-class="sequence"
     *  column="ID"
     */
	public java.lang.Integer getId () {
		return _id;
	}

	/**
	 * Set the unique identifier of this class
	 * @param _id the new ID
	 */
	public void setId (java.lang.Integer _id) {
		this._id = _id;
		this.hashCode = Integer.MIN_VALUE;
	}


	/**
	 * Return the value associated with the column: AD_CLIENT_ID
	 */
	public java.lang.Integer getAdClientId () {
		return _adClientId;
	}

	/**
	 * Set the value related to the column: AD_CLIENT_ID
	 * @param _adClientId the AD_CLIENT_ID value
	 */
	public void setAdClientId (java.lang.Integer _adClientId) {
		this._adClientId = _adClientId;
	}


	/**
	 * Return the value associated with the column: AD_ORG_ID
	 */
	public java.lang.Integer getAdOrgId () {
		return _adOrgId;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrgId the AD_ORG_ID value
	 */
	public void setAdOrgId (java.lang.Integer _adOrgId) {
		this._adOrgId = _adOrgId;
	}


	/**
	 * Return the value associated with the column: NAME
	 */
	public java.lang.String getName () {
		return _name;
	}

	/**
	 * Set the value related to the column: NAME
	 * @param _name the NAME value
	 */
	public void setName (java.lang.String _name) {
		this._name = _name;
	}


	/**
	 * Return the value associated with the column: DESCRIPTION
	 */
	public java.lang.String getDescription () {
		return _description;
	}

	/**
	 * Set the value related to the column: DESCRIPTION
	 * @param _description the DESCRIPTION value
	 */
	public void setDescription (java.lang.String _description) {
		this._description = _description;
	}


	/**
	 * Return the value associated with the column: ISSUMMARY
	 */
	public java.lang.String getIsSummary () {
		return _isSummary;
	}

	/**
	 * Set the value related to the column: ISSUMMARY
	 * @param _isSummary the ISSUMMARY value
	 */
	public void setIsSummary (java.lang.String _isSummary) {
		this._isSummary = _isSummary;
	}


	/**
	 * Return the value associated with the column: C_BP_GROUP_ID
	 */
	public java.lang.Integer getCBpGroupId () {
		return _cBpGroupId;
	}

	/**
	 * Set the value related to the column: C_BP_GROUP_ID
	 * @param _cBpGroupId the C_BP_GROUP_ID value
	 */
	public void setCBpGroupId (java.lang.Integer _cBpGroupId) {
		this._cBpGroupId = _cBpGroupId;
	}


	/**
	 * Return the value associated with the column: ISVENDOR
	 */
	public java.lang.String getIsVendor () {
		return _isVendor;
	}

	/**
	 * Set the value related to the column: ISVENDOR
	 * @param _isVendor the ISVENDOR value
	 */
	public void setIsVendor (java.lang.String _isVendor) {
		this._isVendor = _isVendor;
	}


	/**
	 * Return the value associated with the column: ISCUSTOMER
	 */
	public java.lang.String getIsCustomer () {
		return _isCustomer;
	}

	/**
	 * Set the value related to the column: ISCUSTOMER
	 * @param _isCustomer the ISCUSTOMER value
	 */
	public void setIsCustomer (java.lang.String _isCustomer) {
		this._isCustomer = _isCustomer;
	}


	/**
	 * Return the value associated with the column: ISEMPLOYEE
	 */
	public java.lang.String getIsEmployee () {
		return _isEmployee;
	}

	/**
	 * Set the value related to the column: ISEMPLOYEE
	 * @param _isEmployee the ISEMPLOYEE value
	 */
	public void setIsEmployee (java.lang.String _isEmployee) {
		this._isEmployee = _isEmployee;
	}


	/**
	 * Return the value associated with the column: OWNERID
	 */
	public java.lang.Integer getOwnerId () {
		return _ownerId;
	}

	/**
	 * Set the value related to the column: OWNERID
	 * @param _ownerId the OWNERID value
	 */
	public void setOwnerId (java.lang.Integer _ownerId) {
		this._ownerId = _ownerId;
	}


	/**
	 * Return the value associated with the column: MODIFIERID
	 */
	public java.lang.Integer getModifierId () {
		return _modifierId;
	}

	/**
	 * Set the value related to the column: MODIFIERID
	 * @param _modifierId the MODIFIERID value
	 */
	public void setModifierId (java.lang.Integer _modifierId) {
		this._modifierId = _modifierId;
	}


	/**
	 * Return the value associated with the column: CREATIONDATE
	 */
	public java.util.Date getCreationDate () {
		return _creationDate;
	}

	/**
	 * Set the value related to the column: CREATIONDATE
	 * @param _creationDate the CREATIONDATE value
	 */
	public void setCreationDate (java.util.Date _creationDate) {
		this._creationDate = _creationDate;
	}


	/**
	 * Return the value associated with the column: MODIFIEDDATE
	 */
	public java.util.Date getModifiedDate () {
		return _modifiedDate;
	}

	/**
	 * Set the value related to the column: MODIFIEDDATE
	 * @param _modifiedDate the MODIFIEDDATE value
	 */
	public void setModifiedDate (java.util.Date _modifiedDate) {
		this._modifiedDate = _modifiedDate;
	}


	/**
	 * Return the value associated with the column: ISACTIVE
	 */
	public java.lang.String getIsActive () {
		return _isActive;
	}

	/**
	 * Set the value related to the column: ISACTIVE
	 * @param _isActive the ISACTIVE value
	 */
	public void setIsActive (java.lang.String _isActive) {
		this._isActive = _isActive;
	}


	/**
     * @hibernate.property
     *  column=AD_ORG_ID
	 */
	public nds.model.AdOrg getAdOrg () {
		return this._adOrg;
	}

	/**
	 * Set the value related to the column: AD_ORG_ID
	 * @param _adOrg the AD_ORG_ID value
	 */
	public void setAdOrg (nds.model.AdOrg _adOrg) {
		this._adOrg = _adOrg;
	}


	/**
     * @hibernate.property
     *  column=C_BP_GROUP_ID
	 */
	public nds.model.CBpGroup getCBpGroup () {
		return this._cBpGroup;
	}

	/**
	 * Set the value related to the column: C_BP_GROUP_ID
	 * @param _cBpGroup the C_BP_GROUP_ID value
	 */
	public void setCBpGroup (nds.model.CBpGroup _cBpGroup) {
		this._cBpGroup = _cBpGroup;
	}


	/**
	 * Return the value associated with the column: CBpartnerLocationSet
	 */
	public java.util.Set getCBpartnerLocationSet () {
		return this._cBpartnerLocationSet;
	}

	/**
	 * Set the value related to the column: CBpartnerLocationSet
	 * @param _cBpartnerLocationSet the CBpartnerLocationSet value
	 */
	public void setCBpartnerLocationSet (java.util.Set _cBpartnerLocationSet) {
		this._cBpartnerLocationSet = _cBpartnerLocationSet;
	}
	
	public void addToCBpartnerLocationSet (Object obj) {
		if (null == this._cBpartnerLocationSet) this._cBpartnerLocationSet = new java.util.HashSet();
		this._cBpartnerLocationSet.add(obj);
	}



	/**
	 * Return the value associated with the column: CBpBankAccountSet
	 */
	public java.util.Set getCBpBankAccountSet () {
		return this._cBpBankAccountSet;
	}

	/**
	 * Set the value related to the column: CBpBankAccountSet
	 * @param _cBpBankAccountSet the CBpBankAccountSet value
	 */
	public void setCBpBankAccountSet (java.util.Set _cBpBankAccountSet) {
		this._cBpBankAccountSet = _cBpBankAccountSet;
	}
	
	public void addToCBpBankAccountSet (Object obj) {
		if (null == this._cBpBankAccountSet) this._cBpBankAccountSet = new java.util.HashSet();
		this._cBpBankAccountSet.add(obj);
	}



	/**
	 * Return the value associated with the column: UsersSet
	 */
	public java.util.Set getUsersSet () {
		return this._usersSet;
	}

	/**
	 * Set the value related to the column: UsersSet
	 * @param _usersSet the UsersSet value
	 */
	public void setUsersSet (java.util.Set _usersSet) {
		this._usersSet = _usersSet;
	}
	
	public void addToUsersSet (Object obj) {
		if (null == this._usersSet) this._usersSet = new java.util.HashSet();
		this._usersSet.add(obj);
	}



	public boolean equals (Object obj) {
		if (null == obj) return false;
		if (!(obj instanceof nds.model.base.BaseCBpartner)) return false;
		else {
			nds.model.base.BaseCBpartner mObj = (nds.model.base.BaseCBpartner) obj;
			if (null == this.getId() || null == mObj.getId()) return false;
			else return (this.getId().equals(mObj.getId()));
		}
	}


	public int hashCode () {
		if (Integer.MIN_VALUE == this.hashCode) {
			if (null == this.getId()) return super.hashCode();
			else {
				String hashStr = this.getClass().getName() + ":" + this.getId().hashCode();
				this.hashCode = hashStr.hashCode();
			}
		}
		return this.hashCode;
	}


	public String toString () {
		return super.toString();
	}

}