package nds.model.dao;

import nds.model.base.BaseMWarehouseDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the M_WAREHOUSE table.
 * Any customizations belong here.
 */
public class MWarehouseDAO extends BaseMWarehouseDAO {
}