package nds.model.dao;

import nds.model.base.BaseSpoDefPriorityDAO;

/**
 * This class has been automatically generated by Hibernate Synchronizer.
 * For more information or documentation, visit The Hibernate Synchronizer page
 * at http://www.binamics.com/hibernatesync or contact Joe Hudson at joe@binamics.com.
 *
 * This is the object class that relates to the SPO_DEF_PRIORITY table.
 * Any customizations belong here.
 */
public class SpoDefPriorityDAO extends BaseSpoDefPriorityDAO {
}