spo begin.log

CREATE TABLESPACE RMANTS DATAFILE 
  'E:\oracle\oradata\cc\rmants.DBF' SIZE 200M AUTOEXTEND ON NEXT 10M MAXSIZE 2000M
LOGGING
ONLINE
PERMANENT
EXTENT MANAGEMENT LOCAL AUTOALLOCATE
BLOCKSIZE 8K
SEGMENT SPACE MANAGEMENT MANUAL;


CREATE USER rman888 
  IDENTIFIED BY rman 
  DEFAULT TABLESPACE rmants
  TEMPORARY TABLESPACE TEMP
  PROFILE DEFAULT
  ACCOUNT UNLOCK
  QUOTA UNLIMITED ON rmants;

GRANT RECOVERY_CATALOG_OWNER TO RMAN888;

GRANT CONNECT,RESOURCE TO RMAN888;

exit

